### ISSUE TITLE
Texture pack Problems

### ISSUE THREAD

**Issue by quantum1299** [AbrarSyed/SecretRoomsMod-forge#136]
![2014-07-27_19 32 23](https://cloud.githubusercontent.com/assets/8284657/3715670/5ad62702-15f0-11e4-9d6a-b94a5143a3d5.png)
![2014-07-27_19 32 18](https://cloud.githubusercontent.com/assets/8284657/3715671/5e81541c-15f0-11e4-9713-59d43f1dd28d.png)

Not sure if i should report it to you or the texture pack creator, but when using a texture pack (specifically sphax purebdcraft) the secretrooms blocks are a lighter shade than the actual blocks, so it would be a dead giveaway.

**Comment by AbrarSyed** [comment]
This seems to be fixed.. or at the very least I cannot reproduce in my development environment.
