### ISSUE TITLE
Secret Redstone not functioning properly

### ISSUE THREAD

**Issue by challenger1** [AbrarSyed/SecretRoomsMod-forge#138]
Sometimes, when i build using secret redstone, when i create a redstone signal, when the signal is ceased, some of the secret redstone blocks are still active. This is very annoying when trying to create a secret room, because if it happens once, it will always (as far as i can tell) have the same problem. I am using minecraft version 1.6.4

**Comment by AbrarSyed** [comment]
1.6.4 was unsupported even at the time this issue was created.
also I cant reproduce this...
