### ISSUE TITLE
One-Way Glass crash

### ISSUE THREAD

**Issue by DavidDiack** [AbrarSyed/SecretRoomsMod-forge#146]
Hi there.

When I try to place one-way glass down, my friends get kicked from the server with a message saying:
"A fatal error was experienced"

SecretRoomsMod version:  1.7.10-4.7.1.372
MinecraftForge version:      10.13.0.1208
Minecraft version:                1.7.10

**Comment by AbrarSyed** [comment]
need more info than that. Please make a new issue with more info if this still exists...
