### ISSUE TITLE
Nothing works without crashing world (not game)

### ISSUE THREAD

**Issue by randompersons** [AbrarSyed/SecretRoomsMod-forge#150]
Version of Minecraft: 1.7.10

Version of Secret Rooms Mod (File Name): secretroomsmod-1.7.10-4.7.0.370

Version of Forge (File Name): 1.7.10-Forge10.13.2.123

All I did was start up minecraft with the right version of Forge, and then made a new world with "generate structures" off, world type set to default, cheats on, and no bonus chest. Plus, it was a creative world. Once in the world, I went to the Secret Rooms inventory tab, got a "ghost block", and when I placed it down the world crashed (not the game), and said "Connection Lost: A fatal error has occurred, this connection is terminated". It also had a button that said "Back to tile screen". If I try to go back onto the world, it brings me to the same "Connection Lost" message.

Screen Shot Link: https://cloud.githubusercontent.com/assets/9371370/4759876/0bda0610-5aeb-11e4-8f84-f56f7031f724.png

Minecraft Forums Username: randomperson500

**Comment by AbrarSyed** [comment]
il need a server log for this.

**Comment by AbrarSyed** [comment]
no info for a long time.....
