### ISSUE TITLE
<secretroomsmod:OneWayGlass> Tile entity crashes server

### ISSUE THREAD

**Issue by skaviouz** [AbrarSyed/SecretRoomsMod-forge#153]
http://pastebin.com/EcLYYV29

Essentially the mod EnviroMine has gravity, and when you mine the block underneath <secretroomsmod:OneWayGlass> it should turn into an entity, hit the ground, then turn back into a block. It instead crashes the server (not the client?), and upon relogging this is what the block looks like. I am assuming this is because the texture is dynamic?

http://puu.sh/cUVHc/ac4c59f347.jpg
p.s. ignore that orange stuff in the background, that is something else I was testing. (not related)

**Comment by AbrarSyed** [comment]
likely fixed by ff2e5062327bc3ccf866829a6ee9820ac3f67333
