### ISSUE TITLE
SRM chooses wrong location for world-files

### ISSUE THREAD

**Issue by olee** [AbrarSyed/SecretRoomsMod-forge#155]
http://pastebin.com/hxzydJET
There should be another way of retrieving the dimension-dir than the one used to get the correct location.

**Comment by AbrarSyed** [comment]
unable to find the method you were talking about. + the current system works fine...

**Comment by olee** [comment]
:sweat: 
That one-line change should fix it.
Didn't check it though - I currently have no time for that as you might have heard :disappointed: 

````
    private File getSaveFile(World world)
    {
        //String worldSaveFolder = world.provider.getSaveFolder();
        String worldSaveFolder = world.getChunkSaveLocation();
        // ......
    }

**Comment by AbrarSyed** [comment]
Except there is no such method in world...
I would have used it if I could find it...

**Comment by olee** [comment]
It's part of WorldServer and not World.

**Comment by olee** [comment]
You just closed it, because you didn't find the method, but you still did not fix it now, did you?
