### ISSUE TITLE
startup NPE

### ISSUE THREAD

**Issue by Sailren** [AbrarSyed/SecretRoomsMod-forge#165]
http://paste.ubuntu.com/9848571/

malisisdoors{1.7.10-1.4.3} is the version i use and this: secretroomsmod{4.7.1}

**Comment by XBlackLeopardX** [comment]
Yeah im getting the same crash
http://pastebin.com/ZdzD80Me

**Comment by AbrarSyed** [comment]
What build number? 380+?

**Comment by XBlackLeopardX** [comment]
forge - 10.13.2.1291
secret rooms 382 but i see there is a 384 out so ill test it

**Comment by XBlackLeopardX** [comment]
still getting a crash with build 384 
http://pastebin.com/7qBUNiNK

**Comment by AbrarSyed** [comment]
fixed now. grab the latest. Was a typo.. spelled malisis doors wrong...
