### ISSUE TITLE
SecretRooms-ownership.dat error

### ISSUE THREAD

**Issue by Cenbes** [AbrarSyed/SecretRoomsMod-forge#168]
Mod does not have ownership.dat in other worlds of fashion or him or not renewed. After artificial putting him already restored.

ERROR from console:

> [07:14:54 WARN]: java.io.FileNotFoundException: ./world/MoCWyvernLair/SecretRooms-ownership.dat (No such file or directory)
> [07:14:54 WARN]: at java.io.FileOutputStream.open(Native Method)
> [07:14:54 WARN]: at java.io.FileOutputStream.(FileOutputStream.java:221)
> [07:14:54 WARN]: at java.io.FileOutputStream.(FileOutputStream.java:171)
> [07:14:54 WARN]: at com.github.abrarsyed.secretroomsmod.common.OwnershipManager.getDataOut(OwnershipManager.java:283)
> [07:14:54 WARN]: at com.github.abrarsyed.secretroomsmod.common.OwnershipManager.saveWorld(OwnershipManager.java:245)
> [07:14:54 WARN]: at com.github.abrarsyed.secretroomsmod.common.OwnershipManager.onWorldSave(OwnershipManager.java:208)
> [07:14:54 WARN]: at cpw.mods.fml.common.eventhandler.ASMEventHandler_145_OwnershipManager_onWorldSave_Save.invoke(.dynamic)
> [07:14:54 WARN]: at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
> [07:14:54 WARN]: at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
> [07:14:54 WARN]: at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1053)
> [07:14:54 WARN]: at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:519)
> [07:14:54 WARN]: at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:823)
> [07:14:54 WARN]: at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
> [07:14:54 WARN]: at java.lang.Thread.run(Thread.java:745)
> [07:14:54 WARN]: java.io.FileNotFoundException: ./world/DIM4/SecretRooms-ownership.dat (No such file or directory)
> [07:14:54 WARN]: at java.io.FileOutputStream.open(Native Method)
> [07:14:54 WARN]: at java.io.FileOutputStream.(FileOutputStream.java:221)
> [07:14:54 WARN]: at java.io.FileOutputStream.(FileOutputStream.java:171)
> [07:14:54 WARN]: at com.github.abrarsyed.secretroomsmod.common.OwnershipManager.getDataOut(OwnershipManager.java:283)
> [07:14:54 WARN]: at com.github.abrarsyed.secretroomsmod.common.OwnershipManager.saveWorld(OwnershipManager.java:245)
> [07:14:54 WARN]: at com.github.abrarsyed.secretroomsmod.common.OwnershipManager.onWorldSave(OwnershipManager.java:208)
> [07:14:54 WARN]: at cpw.mods.fml.common.eventhandler.ASMEventHandler_145_OwnershipManager_onWorldSave_Save.invoke(.dynamic)
> [07:14:54 WARN]: at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
> [07:14:54 WARN]: at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
> [07:14:54 WARN]: at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1053)
> [07:14:54 WARN]: at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:519)
> [07:14:54 WARN]: at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:823)
> [07:14:54 WARN]: at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
> [07:14:54 WARN]: at java.lang.Thread.run(Thread.java:745)
> [07:14:54 WARN]: java.io.FileNotFoundException: ./world/DIM3/SecretRooms-ownership.dat (No such file or directory)
> [07:14:54 WARN]: at java.io.FileOutputStream.open(Native Method)
> [07:14:54 WARN]: at java.io.FileOutputStream.(FileOutputStream.java:221)
> [07:14:54 WARN]: at java.io.FileOutputStream.(FileOutputStream.java:171)
> [07:14:54 WARN]: at com.github.abrarsyed.secretroomsmod.common.OwnershipManager.getDataOut(OwnershipManager.java:283)
> [07:14:54 WARN]: at com.github.abrarsyed.secretroomsmod.common.OwnershipManager.saveWorld(OwnershipManager.java:245)
> [07:14:54 WARN]: at com.github.abrarsyed.secretroomsmod.common.OwnershipManager.onWorldSave(OwnershipManager.java:208)
> [07:14:54 WARN]: at cpw.mods.fml.common.eventhandler.ASMEventHandler_145_OwnershipManager_onWorldSave_Save.invoke(.dynamic)
> [07:14:54 WARN]: at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
> [07:14:54 WARN]: at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
> [07:14:54 WARN]: at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1053)
> [07:14:54 WARN]: at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:519)
> [07:14:54 WARN]: at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:823)
> [07:14:54 WARN]: at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
> [07:14:54 WARN]: at java.lang.Thread.run(Thread.java:745)
> [07:14:54 WARN]: java.io.FileNotFoundException: ./world/DIM5/SecretRooms-ownership.dat (No such file or directory)
> [07:14:54 WARN]: at java.io.FileOutputStream.open(Native Method)
> [07:14:54 WARN]: at java.io.FileOutputStream.(FileOutputStream.java:221)
> [07:14:54 WARN]: at java.io.FileOutputStream.(FileOutputStream.java:171)
> [07:14:54 WARN]: at com.github.abrarsyed.secretroomsmod.common.OwnershipManager.getDataOut(OwnershipManager.java:283)
> [07:14:54 WARN]: at com.github.abrarsyed.secretroomsmod.common.OwnershipManager.saveWorld(OwnershipManager.java:245)
> [07:14:54 WARN]: at com.github.abrarsyed.secretroomsmod.common.OwnershipManager.onWorldSave(OwnershipManager.java:208)
> [07:14:54 WARN]: at cpw.mods.fml.common.eventhandler.ASMEventHandler_145_OwnershipManager_onWorldSave_Save.invoke(.dynamic)
> [07:14:54 WARN]: at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
> [07:14:54 WARN]: at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
> [07:14:54 WARN]: at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1053)
> [07:14:54 WARN]: at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:519)
> [07:14:54 WARN]: at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:823)
> [07:14:54 WARN]: at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)

**Comment by AbrarSyed** [comment]
Been fixed. Please get latest version from files.minecraftforge.net/SecretRoomsMod

**Comment by Alaberti** [comment]
I'm getting a similar issue and I am using version 4.7.1.404 (the latest to my knowledge). it appears in reference to Galacticraft dimensions. It does not appear to crash anything at any rate so I do no believe it is a critical issue.

http://pastebin.com/NEt6KwLx

**Comment by AbrarSyed** [comment]
please make a new issue for that.
