### ISSUE TITLE
Mod crashes server

### ISSUE THREAD

**Issue by groveham** [AbrarSyed/SecretRoomsMod-forge#171]
Minecraft version: 1.7.10
    SecretRoomsMod version: secretroomsmod-1.7.10-4.7.1.376.jar
    MinecraftForge version: 1232
    an explanation of what you did to get your error: A player on my server pressed a secret rooms button as far as I'm aware. 
    if applicable, an error report: http://pastebin.com/Qd9t64Xs
    your MinecraftForums username: groveham

**Comment by AbrarSyed** [comment]
Update. That's an old version.
