### ISSUE TITLE
Waila shows SecretRooms info

### ISSUE THREAD

**Issue by dark-skript** [AbrarSyed/SecretRoomsMod-forge#174]
HI, this is probably not a bug but just an unimplemented or overlooked feature, but Waila will show anything from the SecretRooms mod which kinda defeats the purpose of this mod, So is there a possibility you will add Waila support to show the Camouflaged block instead?

Cheers.

**Comment by dark-skript** [comment]
Edit: Ive noticed you have Waila support, it could be the latest version of Waila thats broken?

**Comment by dark-skript** [comment]
Crash Probably also related: http://pastebin.com/mhFbQYT9

**Comment by AbrarSyed** [comment]
It looks like people can see your blocks because you are the owner of your blocks. For other people, waila doesn't give any information. However that crash is indeed worth looking into.

**Comment by jimmon89** [comment]
I had the exact same crash... in my technic mod pack, i just updated to the latest version which as of writing is 4.7.1.404 and im using the latest recommended forge which is 10.13.2.1291. my mod pack is 
http://www.technicpack.net/modpack/jimmons-epic-pack.570966 if u need that for the modlist.
