### ISSUE TITLE
Look at a Camo Trap door crashes the client out

### ISSUE THREAD

**Issue by djoveryde** [AbrarSyed/SecretRoomsMod-forge#175]
If a player looks at their Camo trap door their client will crash completely out. This has only happened in the latest update.

http://pastebin.com/zmYbLmkH

**Comment by AbrarSyed** [comment]
What version of SecretRoomsMod?

**Comment by djoveryde** [comment]
secretroomsmod-1.7.10-4.7.1.409

**Comment by eoistana** [comment]
I have the same issue, looking at a camo trapdoor crashes me to the desktop.
Removing WAILA, lets me enter the game and look at the trapdoor.

**Comment by AbrarSyed** [comment]
I have not been able to reproduce this issue... Can someone provide a specific circumstance where this happens?

**Comment by eoistana** [comment]
Waila-1.5.9_1.7.10
WailaPlugins-MC1.7.10-0.0.1-13
secretroomsmod-1.7.10-4.7.1.409

**Comment by AbrarSyed** [comment]
I mean like.. how to reproduce? Does someone just place a trap door and then look at it? because doing that does not crash for me.

**Comment by eoistana** [comment]
Yes, at least for me. Placing and looking at the trapdoor while Waila is active, causes the crash. I can remove Waila, and place a trapdoor, no problem. But, if I reactivate Waila, and look at the trapdoor, I crash again.

**Comment by AbrarSyed** [comment]
I have a feeling that this is the result of interaction with another mod. I suggest you try from a base of just WAILA and the SecretRoomsMod, and then slowly add your other mods one by one till the error occurs. If it happens with only WAILA and SecretRooms.. I am really stumped as to why that happens...
