### ISSUE TITLE
Client crashes on server, server keeps running

### ISSUE THREAD

**Issue by hanakocz** [AbrarSyed/SecretRoomsMod-forge#178]
We also tried WAILA version 1.5.10 (newest version) , it was still same

---- Minecraft Crash Report ----
// Everything's going to plan. No, really, that was supposed to happen.

Time: 22.3.15 22:49
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at com.github.abrarsyed.secretroomsmod.common.OwnershipManager.getOwner(OwnershipManager.java:125)
	at com.github.abrarsyed.secretroomsmod.common.OwnershipManager.isOwner(OwnershipManager.java:115)
	at com.github.abrarsyed.secretroomsmod.blocks.BlockCamoTrapDoor.getPickBlock(BlockCamoTrapDoor.java:429)
	at com.github.abrarsyed.secretroomsmod.client.waila.WailaProvider.getWailaStack(WailaProvider.java:60)
	at mcp.mobius.waila.overlay.RayTracing.getIdentifierItems(RayTracing.java:144)
	at mcp.mobius.waila.overlay.RayTracing.getIdentifierStack(RayTracing.java:92)
	at mcp.mobius.waila.overlay.RayTracing.getTargetStack(RayTracing.java:61)
	at mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:75)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_244_WailaTickHandler_tickClient_ClientTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:330)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2052)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.github.abrarsyed.secretroomsmod.common.OwnershipManager.getOwner(OwnershipManager.java:125)
	at com.github.abrarsyed.secretroomsmod.common.OwnershipManager.isOwner(OwnershipManager.java:115)
	at com.github.abrarsyed.secretroomsmod.blocks.BlockCamoTrapDoor.getPickBlock(BlockCamoTrapDoor.java:429)
	at com.github.abrarsyed.secretroomsmod.client.waila.WailaProvider.getWailaStack(WailaProvider.java:60)
	at mcp.mobius.waila.overlay.RayTracing.getIdentifierItems(RayTracing.java:144)
	at mcp.mobius.waila.overlay.RayTracing.getIdentifierStack(RayTracing.java:92)
	at mcp.mobius.waila.overlay.RayTracing.getTargetStack(RayTracing.java:61)
	at mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:75)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_244_WailaTickHandler_tickClient_ClientTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:330)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [GCEntityClientPlayerMP['LordGuma'/260391, l='MpServer', x=-258,96, y=71,50, z=511,41]]
	Chunk stats: MultiplayerChunkCache: 5, 5
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (302,68,277), Chunk: (at 14,4,5 in 18,17; contains blocks 288,0,272 to 303,255,287), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 435357093 game time, 42684252 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: adventure (ID 2). Hardcore: false. Cheats: false
	Forced entities: 44 total; [EntityPig['Pig'/260419, l='MpServer', x=-292,31, y=71,00, z=454,50], EntitySheep['Sheep'/260417, l='MpServer', x=-289,34, y=69,00, z=448,19], EntityMysticEnderminion['Mystic Enderminion'/260416, l='MpServer', x=-208,16, y=64,00, z=513,59], EntityMysticEnderminion['Mystic Enderminion'/260423, l='MpServer', x=-205,19, y=64,00, z=512,88], EntitySheep['Sheep'/260427, l='MpServer', x=-319,84, y=75,00, z=450,06], EntitySkeleton['Skeleton'/260426, l='MpServer', x=-246,50, y=39,00, z=567,50], EntitySkeleton['Skeleton'/260425, l='MpServer', x=-247,50, y=39,00, z=570,50], EntityChicken['Chicken'/260430, l='MpServer', x=-221,47, y=64,00, z=451,53], EntitySheep['Sheep'/260429, l='MpServer', x=-218,53, y=45,00, z=448,81], EntitySheep['Sheep'/260428, l='MpServer', x=-304,50, y=69,00, z=451,19], GCEntityClientPlayerMP['LordGuma'/260391, l='MpServer', x=-258,96, y=71,50, z=511,41], EntitySkeleton['Skeleton'/260435, l='MpServer', x=-295,69, y=67,00, z=572,31], EntityWitch['Witch'/260434, l='MpServer', x=-296,69, y=67,00, z=574,16], EntityWitch['Witch'/260433, l='MpServer', x=-296,56, y=67,00, z=573,31], EntityPig['Pig'/260432, l='MpServer', x=-294,19, y=72,00, z=570,63], EntitySkeleton['Skeleton'/260437, l='MpServer', x=-299,50, y=72,00, z=561,84], EntitySkeleton['Skeleton'/260436, l='MpServer', x=-295,28, y=67,00, z=573,28], EntitySkeleton['Skeleton'/260442, l='MpServer', x=-305,00, y=69,00, z=571,31], EntityChicken['Chicken'/260441, l='MpServer', x=-309,47, y=75,00, z=560,53], EntityCow['Cow'/260440, l='MpServer', x=-305,53, y=72,00, z=572,56], EntityButterfly['entity.Forestry.butterflyGE.name'/260395, l='MpServer', x=-241,38, y=74,00, z=485,50], EntityButterfly['entity.Forestry.butterflyGE.name'/260394, l='MpServer', x=-270,38, y=78,28, z=524,44], EntityEnderminion['Enderminion'/260393, l='MpServer', x=-246,50, y=70,00, z=500,91], EntityEnderminion['Enderminion'/260392, l='MpServer', x=-257,13, y=69,88, z=495,91], EntityCartChest['entity.MinecartChest.name'/260399, l='MpServer', x=-236,50, y=24,85, z=501,53], EntityCartChest['entity.MinecartChest.name'/260398, l='MpServer', x=-236,50, y=24,85, z=499,97], EntityCartChest['entity.MinecartChest.name'/260397, l='MpServer', x=-236,50, y=24,85, z=498,69], EntityButterfly['entity.Forestry.butterflyGE.name'/260396, l='MpServer', x=-249,69, y=70,94, z=480,06], EntityButterfly['entity.Forestry.butterflyGE.name'/260403, l='MpServer', x=-277,38, y=74,00, z=529,03], EntityButterfly['entity.Forestry.butterflyGE.name'/260402, l='MpServer', x=-257,47, y=81,72, z=530,44], EntityCartAnchorPersonal['Personal Anchor Cart'/260401, l='MpServer', x=-235,81, y=24,85, z=504,50], EntityCartChest['entity.MinecartChest.name'/260400, l='MpServer', x=-236,50, y=24,85, z=503,09], EntityChicken['Chicken'/260407, l='MpServer', x=-251,69, y=65,66, z=470,84], EntityChicken['Chicken'/260406, l='MpServer', x=-251,19, y=65,72, z=470,84], EntityButterfly['entity.Forestry.butterflyGE.name'/260405, l='MpServer', x=-238,38, y=70,00, z=484,63], EntityButterfly['entity.Forestry.butterflyGE.name'/260404, l='MpServer', x=-277,41, y=68,00, z=468,63], EntityWitch['Witch'/260411, l='MpServer', x=-313,13, y=77,00, z=509,56], EntityButterfly['entity.Forestry.butterflyGE.name'/260410, l='MpServer', x=-230,72, y=68,00, z=473,38], EntityButterfly['entity.Forestry.butterflyGE.name'/260409, l='MpServer', x=-297,72, y=100,34, z=537,94], EntityItem['item.item.egg'/260408, l='MpServer', x=-251,78, y=64,13, z=470,88], EntityButterfly['entity.Forestry.butterflyGE.name'/260415, l='MpServer', x=-220,59, y=69,00, z=480,50], EntityChicken['Chicken'/260414, l='MpServer', x=-216,47, y=70,00, z=486,56], EntityCow['Cow'/260413, l='MpServer', x=-249,53, y=66,00, z=460,50], EntityButterfly['entity.Forestry.butterflyGE.name'/260412, l='MpServer', x=-266,59, y=76,00, z=545,63]]
	Retry entities: 0 total; []
	Server brand: cauldron,craftbukkit,mcpc,fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2432)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:916)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_31, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 631171320 bytes (601 MB) / 1615331328 bytes (1540 MB) up to 3044540416 bytes (2903 MB)
	Mod Pack: Unknown / None
	LiteLoader Mods: 2 loaded mod(s)
          - WorldEditCUI version 1.7.10_00
          - VoxelMap version 1.2.3
	LaunchWrapper: 35 active transformer(s)
          - Transformer: cpw.mods.fml.common.asm.transformers.PatchingTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.MarkerTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.SideTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.EventSubscriptionTransformer
          - Transformer: com.spacechase0.minecraft.spacecore.asm.block.BlockDestructionTransformer
          - Transformer: com.spacechase0.minecraft.spacecore.asm.network.PacketInterceptTransformer
          - Transformer: com.spacechase0.minecraft.spacecore.asm.render.TextureInterceptTransformer
          - Transformer: com.spacechase0.minecraft.spacecore.asm.mcp.LoaderModInfoTransformer
          - Transformer: com.spacechase0.minecraft.spacecore.asm.mod.ModInitTransformer
          - Transformer: com.spacechase0.minecraft.spacecore.asm.config.GuiFactoryTransformer
          - Transformer: appeng.transformer.asm.ASMIntegration
          - Transformer: codechicken.lib.asm.ClassHeirachyManager
          - Transformer: codechicken.core.asm.InterfaceDependancyTransformer
          - Transformer: codechicken.core.asm.TweakTransformer
          - Transformer: codechicken.core.asm.DelegatedTransformer
          - Transformer: codechicken.core.asm.DefaultImplementationTransformer
          - Transformer: micdoodle8.mods.miccore.MicdoodleTransformer
          - Transformer: codechicken.nei.asm.NEITransformer
          - Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer
          - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.DeobfuscationTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.AccessTransformer
          - Transformer: net.minecraftforge.transformers.ForgeAccessTransformer
          - Transformer: appeng.transformer.asm.ASMTweaker
          - Transformer: codechicken.core.asm.CodeChickenAccessTransformer
          - Transformer: micdoodle8.mods.miccore.MicdoodleAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ItemStackTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.TerminalTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LiteLoaderEventInjectionTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.MinecraftOverlayTransformer
          - Transformer: com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer
          - Transformer: com.thevoxelbox.voxelmap.litemod.VoxelMapTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAPITransformer
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3266m -XX:MaxPermSize=128m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 45 mods loaded, 45 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	FML{7.10.85.1291} [Forge Mod Loader] (modpack.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Forge{10.13.2.1291} [Minecraft Forge] (modpack.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	appliedenergistics2-core{rv2-beta-14} [AppliedEnergistics2 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	CodeChickenCore{1.0.4.35} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	NotEnoughItems{1.0.4.90} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.90-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	SC0_SpaceCore{0.7.9} [SpaceCore] ([1.7.10] SpaceCore 0.7.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	SC0_ToxicRain{1.0.3} [Toxic Rain] ([1.7.2] Toxic Rain 1.0.3.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	appliedenergistics2{rv2-beta-14} [Applied Energistics 2] (appliedenergistics2-rv2-beta-14.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BiblioCraft{1.9.2} [BiblioCraft] (BiblioCraft[v1.9.2][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Core{6.4.4} [BuildCraft] (buildcraft-6.4.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Transport{6.4.4} [BC Transport] (buildcraft-6.4.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Silicon{6.4.4} [BC Silicon] (buildcraft-6.4.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Builders{6.4.4} [BC Builders] (buildcraft-6.4.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Energy{6.4.4} [BC Energy] (buildcraft-6.4.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Factory{6.4.4} [BC Factory] (buildcraft-6.4.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Compat{6.4.0} [BuildCraft Compat] (buildcraft-compat-6.4.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	CarpentersBlocks{3.3.4.1} [Carpenter's Blocks] (Carpenter's Blocks v3.3.4.1 - MC 1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	chisel{2.2.1} [Chisel] (Chisel 2-2.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	cep{1.5.1 - 1.7.2} [Craftable End Portal] (CraftableEndPortal-1.5.1 - 1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	CustomOreGen{1.2.13} [Custom Ore Generation] (CustomOreGen-1.7.10-1.2.13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Waila{1.5.8} [Waila] (Waila-1.5.8b_dev1_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	extracells{2.2.59} [ExtraCells] (ExtraCells-1.7.10-2.2.59b89.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	farlanders{1.2b} [The Farlanders] (farlanders-1.7.10-v1.2b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	IC2{2.2.675-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.675-experimental.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Forestry{3.5.0.486-unstable} [Forestry for Minecraft] (forestry_1.7.10-3.5.0.486-unstable.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	GalacticraftCore{3.0.10} [Galacticraft Core] (GalacticraftCore-1.7-3.0.10.298.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	GalacticraftMars{3.0.10} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.10.298.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	PFAAGeologica{0.2.23} [Geologica] (PFAA-1.7.10-0.2.23.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Railcraft{9.5.0.0} [Railcraft] (Railcraft_1.7.10-9.5.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	gregtech{MC1710} [GregTech] (gregtech_1.7.10-5.07.07.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	galacticgreg{0.5} [Galactic Greg] (GalacticGreg-0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	GemBlocksForGreg{1.0} [GemBlocksForGreg] (GemBlocksForGreg-1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	IC2BackpackHUD{3.0} [IC2 Backpack HUD] (IC2 Backpack HUD v3.0 - MC 1.7.10.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	IC2LaserFix{2.0} [IC2 Laser Fix] (IC2LaserFix-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MineMenu{1.2.0} [MineMenu] (MineMenu-1.7.10-1.2.0.B44-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MineTweaker3{3.0.9B} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.9C.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MultiWorld{1.2.7} [Multi World] (Multiworld-1.7.2-v-1.2.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	NBTEdit{1.7.2.2} [In-game NBTEdit] (NBTEdit_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	neiintegration{1.0.0} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	PFAAChemica{0.2.23} [Chemica] (PFAA-1.7.10-0.2.23.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	secretroomsmod{4.7.1} [The SecretRoomsMod] (secretroomsmod-1.7.10-4.7.1.409.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ztech{0.0.2} [Ztech] (Ztech-1.7.10-0.0.2_beta.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	AE2 Version: beta rv2-beta-14 for Forge 10.13.2.1291
	AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:ON, BC:ON, MJ6:OFF, MJ5:OFF, RF:ON, RFItem:ON, MFR:OFF, DSU:OFF, FZ:OFF, FMP:OFF, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:OFF, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
	Launched Version: 1.7.10-Forge10.13.2.1291
	LWJGL: 2.9.1
	OpenGL: ATI Radeon HD 3200 Graphics GL version 3.3.11672 Compatibility Profile Context, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by AbrarSyed** [comment]
possibly the same as #175 need more info.

**Comment by hanakocz** [comment]
To add, the crash is on login of player,who has secret doors in house.
Possible he was looking at them

**Comment by AbrarSyed** [comment]
So possibly a duplicate.. probably same root problem... hmm...

**Comment by hanakocz** [comment]
Yeah, but at least here is crash log. The topic you linked had nothing. Can try to post it to waila bugtracker, but this happened just after SecretRooms upgrade:)

**Comment by hanakocz** [comment]
As how as I tested it, it looks like fixed. Thanks for fast fix :)
I will let the player who experineced it to tet it more, if anything goes wrong, I will be right back here :)
