### ISSUE TITLE
Server crash with Mailis doors

### ISSUE THREAD

**Issue by ruyanve** [AbrarSyed/SecretRoomsMod-forge#179]
Since the last update of Mailis doors my server crashes whenever someone interacts with camo doors.
Here's the log: http://pastebin.com/tC80rJNb

Maybe @Ordinastie knows whats happening? :)

Cheers guys

**Comment by AbrarSyed** [comment]
For now, temporarily, you should be able to disable MalsisDoors compat in the config file.

**Comment by ruyanve** [comment]
Did that already, one of my guys managed to crash the server after I changed to config tho. I'll try to get more info on that and will try to reproduce once I get home.
