### ISSUE TITLE
Camo trap door crashed me

### ISSUE THREAD

**Issue by hue1234** [AbrarSyed/SecretRoomsMod-forge#192]
http://pastebin.com/HYV4nxRi

Camo trap door when i looked at it

**Comment by Maldaris** [comment]
I also have this error, with an identical stack trace.

**Comment by PatoTheBest** [comment]
@AbrarSyed This error was fixed in https://github.com/AbrarSyed/SecretRoomsMod-forge/commit/2e1d39c4e050e8f2078596cd3b19f9cfd7d43f62 but you never updated the file in curse

**Comment by AbrarSyed** [comment]
oh..well then.. thanks for the heads-up. Il put it on curseforge now...

**Comment by PatoTheBest** [comment]
Thanks, works like a charm!
