### ISSUE TITLE
Crash with Secret Player Plate

### ISSUE THREAD

**Issue by Akitori** [AbrarSyed/SecretRoomsMod-forge#196]
A user of mine can't connect to the server after placing a secret pressure plate.

However the server keeps throwing a error at me after placing it, consisting of this

`17.11 23:04:08 [Server] Server thread/WARN Failed to handle packet for /24.251.174.215:60084 17.11 23:04:08 [Server] INFO net.minecraft.util.ReportedException: Ticking player 17.11 23:04:08 [Server] INFO at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:459) ~[oq.class:?] 17.11 23:04:08 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) ~[pa.class:?] 17.11 23:04:08 [Server] INFO at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?] 17.11 23:04:08 [Server] INFO at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?] 17.11 23:04:08 [Server] INFO at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:179) [oz.class:?] 17.11 23:04:08 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788) [MinecraftServer.class:?] 17.11 23:04:08 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?] 17.11 23:04:08 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?] 17.11 23:04:08 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?] 17.11 23:04:08 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152] 17.11 23:04:08 [Server] INFO Caused by: java.lang.NoSuchMethodError: net.minecraft.util.math.AxisAlignedBB.<init>(Lnet/minecraft/util/math/Vec3d;Lnet/minecraft/util/math/Vec3d;)V 17.11 23:04:08 [Server] INFO at com.wynprice.secretroomsmod.base.BaseFakePressurePlate.calculateState(BaseFakePressurePlate.java:51) ~[BaseFakePressurePlate.class:?] 17.11 23:04:08 [Server] INFO at com.wynprice.secretroomsmod.base.BaseFakePressurePlate.func_176199_a(BaseFakePressurePlate.java:35) ~[BaseFakePressurePlate.class:?] 17.11 23:04:08 [Server] INFO at net.minecraft.entity.Entity.func_70091_d(Entity.java:927) ~[vg.class:?] 17.11 23:04:08 [Server] INFO at net.minecraft.entity.EntityLivingBase.func_191986_a(EntityLivingBase.java:1945) ~[vp.class:?] 17.11 23:04:08 [Server] INFO at net.minecraft.entity.player.EntityPlayer.func_191986_a(EntityPlayer.java:1823) ~[aed.class:?] 17.11 23:04:08 [Server] INFO at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2380) ~[vp.class:?] 17.11 23:04:08 [Server] INFO at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:511) ~[aed.class:?] 17.11 23:04:08 [Server] INFO at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2166) ~[vp.class:?] 17.11 23:04:08 [Server] INFO at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:232) ~[aed.class:?] 17.11 23:04:08 [Server] INFO at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) ~[oq.class:?] 17.11 23:04:08 [Server] INFO ... 9 more 17.11 23:04:08 [Server] Server thread/WARN Failed to handle packet for /24.251.174.215:60084 17.11 23:04:08 [Server] INFO net.minecraft.util.ReportedException: Ticking player 17.11 23:04:08 [Server] INFO at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:459) ~[oq.class:?] 17.11 23:04:08 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) ~[pa.class:?] 17.11 23:04:08 [Server] INFO at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?] 17.11 23:04:08 [Server] INFO at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?] 17.11 23:04:08 [Server] INFO at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:179) [oz.class:?] 17.11 23:04:08 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788) [MinecraftServer.class:?] 17.11 23:04:08 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?] 17.11 23:04:08 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?] 17.11 23:04:08 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?] 17.11 23:04:08 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152] 17.11 23:04:08 [Server] INFO Caused by: java.lang.NoSuchMethodError: net.minecraft.util.math.AxisAlignedBB.<init>(Lnet/minecraft/util/math/Vec3d;Lnet/minecraft/util/math/Vec3d;)V 17.11 23:04:08 [Server] INFO at com.wynprice.secretroomsmod.base.BaseFakePressurePlate.calculateState(BaseFakePressurePlate.java:51) ~[BaseFakePressurePlate.class:?] 17.11 23:04:08 [Server] INFO at com.wynprice.secretroomsmod.base.BaseFakePressurePlate.func_176199_a(BaseFakePressurePlate.java:35) ~[BaseFakePressurePlate.class:?] 17.11 23:04:08 [Server] INFO at net.minecraft.entity.Entity.func_70091_d(Entity.java:927) ~[vg.class:?] 17.11 23:04:08 [Server] INFO at net.minecraft.entity.EntityLivingBase.func_191986_a(EntityLivingBase.java:1945) ~[vp.class:?] 17.11 23:04:08 [Server] INFO at net.minecraft.entity.player.EntityPlayer.func_191986_a(EntityPlayer.java:1823) ~[aed.class:?] 17.11 23:04:08 [Server] INFO at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2380) ~[vp.class:?] 17.11 23:04:08 [Server] INFO at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:511) ~[aed.class:?] 17.11 23:04:08 [Server] INFO at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2166) ~[vp.class:?] 17.11 23:04:08 [Server] INFO at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:232) ~[aed.class:?] 17.11 23:04:08 [Server] INFO at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) ~[oq.class:?] 17.11 23:04:08 [Server] INFO ... 9 more 17.11 23:04:08 [Disconnect] User Tmtravlr has disconnected, reason: Internal server error`

**Comment by Wyn-Price** [comment]
Is it just that user or is it everyone

**Comment by Akitori** [comment]
Block was disguised as grass block, forge version was 2509 on both client and server. 

It affected all users as far as i'm aware of.

**Comment by Wyn-Price** [comment]
Does 14.23.0.2502 work for you?

**Comment by Akitori** [comment]
haven't tested that yet, though as its a server with multiple users on it...not sure if its wise to roll back (i even recall some mods requiring 2509)

**Comment by Wyn-Price** [comment]
I'll be able to fix today. I'll also release a new version today. I know how I can fix this

**Comment by Wyn-Price** [comment]
@Akitori fixed versions. Should be uploaded to curseforge in about 10 minutes
