### ISSUE TITLE
Crash with Latest

### ISSUE THREAD

**Issue by Akitori** [AbrarSyed/SecretRoomsMod-forge#198]
I feel like you'll hate me soon enough. Client side crash, log is below. Placed secret gate upon grass. 

[crash-2017-11-19_16.48.53-client.txt](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1486069/crash-2017-11-19_16.48.53-client.txt)

**Comment by Wyn-Price** [comment]
I dont hate you what you are doing helps the mod and makes sure its stable. I figured out this could be an issue but for some reason I didnt test it. Ill be able to fix this and upload it within around 30 minutes

**Comment by Wyn-Price** [comment]
this is taking longer than it usally would because Im moving around and redoing a large portion of the code to make it easier to add/change things in the future
