### ISSUE TITLE
Crash with 5.1.3

### ISSUE THREAD

**Issue by BrisingrAerowing** [AbrarSyed/SecretRoomsMod-forge#199]
[Game Log](https://gist.github.com/BrisingrAerowing/64e33837b08e7debf619f10001aee06a)

This happened on world load, so no crash log. You'll need to view raw to see the whole file. The error is near line 20200.

**Comment by Wyn-Price** [comment]
Yeh i already got this issue #198 
Ive removed the download from curseforge and ive figured out the issue.
