### ISSUE TITLE
Modular Machinary incompat

### ISSUE THREAD

**Issue by NicosaurusRex99** [AbrarSyed/SecretRoomsMod-forge#200]
https://pastebin.com/zBmu5xLh

**Comment by NicosaurusRex99** [comment]
https://github.com/HellFirePvP/ModularMachinery/issues

**Comment by NicosaurusRex99** [comment]
@HellFirePvP

**Comment by HellFirePvP** [comment]
Not my fault - I only get an item's burn time and it seems it fails to get the burn time of a block from secretroomsmod from its default state according to the stacktrace. So. Not on my end.

**Comment by NicosaurusRex99** [comment]
alrighty

**Comment by Wyn-Price** [comment]
Ah right I see what's going on. I rewrote alot of the mod last night, quite late and I just didn't really think fully. I assumed that when getting through material, there would be a world (in either MinecraftServer#getworlds or Minecraft.world) this fix is so easy I can do it from my phone, but I won't be able to upload until later today.

**Comment by NicosaurusRex99** [comment]
Cool.
