### ISSUE TITLE
Server Crash using secret rooms.

### ISSUE THREAD

**Issue by Akitori** [AbrarSyed/SecretRoomsMod-forge#202]
Apparently we're not done fixing bugs yet, sigh. Here's the crash. 

[crash-2017-11-22_23.50.57-server.txt](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1498141/crash-2017-11-22_23.50.57-server.txt)

**Comment by Wyn-Price** [comment]
Ah i didn't see this. I have however fixed this issue in a release I did yesterday. Try running the server again. Im going to release a new version in about 2 hours, when I get home from school.
