### ISSUE TITLE
Redstone is invisible after relogging? (also not solid)

### ISSUE THREAD

**Issue by Akitori** [AbrarSyed/SecretRoomsMod-forge#203]
Yeah, idk why but relogging does that no matter what version is used. Is this a bug?

**Comment by Wyn-Price** [comment]
I'll look into it tomorrow. It's currently 4:12am and I really need to get some sleep

**Comment by Wyn-Price** [comment]
Ok I'll start looking into it now. I think I have an idea of why it's doing it
