### ISSUE TITLE
Low TPs, Random blocks vanishing and more

### ISSUE THREAD

**Issue by Akitori** [AbrarSyed/SecretRoomsMod-forge#205]
https://youtu.be/LLATmAum0Tw

Send help. Forge is 2555, secret rooms is latest

**Comment by Wyn-Price** [comment]
Do you close the server for the bugs to happen or just leave and rejoin. I'll do some testing and I'll look into it, however I do have school exams this week so i won't be able to fix them all straight away

**Comment by Wyn-Price** [comment]
Ill look into it now tho. I have time now

**Comment by Wyn-Price** [comment]
Are there anything in the fml-latest-client.log or fml-latest-server.log

**Comment by Wyn-Price** [comment]
seeing as I cant replicate this, is there any chance I would be able to join your server and do bug testing.  You'd have to turn online-mode to false in the server-properties

**Comment by Akitori** [comment]
Currently the bug happens upon clients rejoining and connecting mainly. Even something as simple as walking out of the chunks.

**Comment by Wyn-Price** [comment]
It sounds like an issue with the NBT saving of tile entities. If I could join your server later it would help as it can be hard to replicate these things

**Comment by Akitori** [comment]
here's something interesting.

![2017-12-02_15 46 28](https://user-images.githubusercontent.com/24502131/33520012-43213302-d778-11e7-842f-70cd8d22e75d.png)

The first red line (after the error) is from a invisible secret redstone. The second is from a visible secret redstone shortly after its placed on grass. Think you're right with the nbt thing.

**Comment by Wyn-Price** [comment]
Ah yes that was a big help. Im think i know why its happening so ill send you the .jar soon. As for the redstone, im not sure whats causing it, but ill look further

**Comment by Wyn-Price** [comment]
Ok ive fixed the issue with the vanishing blocks. The problem was that the packet being sent wasnt fast enough. Ive it now so there is no packet being sent so it works

**Comment by Wyn-Price** [comment]
and for the redstone, I might just rewrite the logic for it, so it can go upwards as well

**Comment by Wyn-Price** [comment]
If your avaliable, I have a .jar that you could test out. Ive rewritten the redstone to be able to go vertical, but it may be buggy

**Comment by Akitori** [comment]
Alright I'm available to test.

**Comment by Wyn-Price** [comment]
[secretroomsmod-5.1.9.zip](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1524771/secretroomsmod-5.1.9.zip)
The wire should be able to go upwards and things, however i didnt change that much of the code, so the lag may still be there

**Comment by Akitori** [comment]
right, some bugs immediately. (secret redstone isn't able to be picked up via hand anymore, only pickaxe it seems?) some circuits using secret redstone needed to be updated but nothing major.

**Comment by Wyn-Price** [comment]
Yeh the logic for the circuits has changed. Is there tps issues still ?

**Comment by Akitori** [comment]
Not as far as i can see.

**Comment by Wyn-Price** [comment]
I'll send you the updated version in a minute then see if you can find any issues with it

**Comment by Wyn-Price** [comment]
[secretroomsmod-5.1.9.zip](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1524836/secretroomsmod-5.1.9.zip)

**Comment by Akitori** [comment]
Everything is working just fine now! Thanks!
