### ISSUE TITLE
In 1.10.2, item recipes are missing and names are incorrect

### ISSUE THREAD

**Issue by LuigiGrande1** [AbrarSyed/SecretRoomsMod-forge#206]
Version: 1.10.2
All the items are named as "item.something.name", and every single recipe is missing (aka you can't craft anything), but the blocks do work. Therefore, you can use the mod in creative, but you can't in survival.
Please fix this.

**Comment by Wyn-Price** [comment]
Ah yes of course. The 1.12.2 recipe system is diffrent to the 1.10.2 and i didnt change it. Also the item names ill look into now.

**Comment by LuigiGrande1** [comment]
Ok. Thank you.

**Comment by LuigiGrande1** [comment]
Oh and also, the "one way glass" block is bugged in 1.10.2. I don't know if other blocks are bugged too, but the one way glass is bugged for sure.

**Comment by Wyn-Price** [comment]
How is it bugged. What Happens

**Comment by LuigiGrande1** [comment]
Don't know why, but now is not bugged anymore... Previously, it looked like colored bars... Maybe was because i had shaders active. My fault.

**Comment by Wyn-Price** [comment]
Yeh things like CTM and optifine shaders will cause issues so be carful

**Comment by LuigiGrande1** [comment]
wait, is the torch lever supposed to output a redstone signal in every situation or it has to be like a lever?

**Comment by Wyn-Price** [comment]
Its meant to be alike a lever.

**Comment by LuigiGrande1** [comment]
well, it acts like a redstone torch, not like a lever, and trapdoors are not working (they just don't open)

**Comment by Wyn-Price** [comment]
Ill look into it tommrow. Theres a few more bugs I want to fix then Ill release a version

**Comment by LuigiGrande1** [comment]
News?

**Comment by Wyn-Price** [comment]
Ah yes sorry for not updating. Im currently working on a new render system for the 1.12.2 version #204. Im nearly finished with it and as soon as I am ill work a new version for 1.10.2 and 1.11.2

**Comment by Wyn-Price** [comment]
Im fixing it now

**Comment by LuigiGrande1** [comment]
Ok :thumbsup:
