### ISSUE TITLE
Slight bug with probes

### ISSUE THREAD

**Issue by Akitori** [AbrarSyed/SecretRoomsMod-forge#207]
Probes don't seem to update everyone's screen. ex: I had a secret stone door, i used a probe to changed it to tnt, but my friend (dr) saw the door as stone still.

**Comment by Wyn-Price** [comment]
Yeh Im rewriting pretty much the whole rendering system to work with optifine, which means the probe switch is gonna be fixed

**Comment by Akitori** [comment]
Hey! Another issue man, sorry. Doors sometimes have that redstone bug as well! (where they turn invisible/cease rendering their thing)

I don't know if it applies to all doors, but mind fixing it?

**Comment by Wyn-Price** [comment]
It's fine reporting bugs, it keeps me busy and makes the mod perfect. I'll look into this but I've just rewrote the render system so I think that might solve it
