### ISSUE TITLE
List of bugs I found in the 1.10.2 version

### ISSUE THREAD

**Issue by Ayasu** [AbrarSyed/SecretRoomsMod-forge#208]
As I mentioned on the project page, I'm very grateful that you updated this awesome mod! As you said, though, there are some problems and I want to go ahead and make a list of some of the ones I've found.

First is the aforementioned name and recipe issue from another post.

The Torch Lever emits a steady redstone signal and cannot be toggled like a lever.

Secret Pressure Plate seems like it 1) emits a steady signal and 2) doesn't work as a pressure plate in front of a door. This is true for all the pressure plates except the Player pressure plate -- that one "works" but does not work in front of doors.

Neither the wooden, nor iron trap doors seem to open at all.

When the Secret Light Detector is broken, it turns into a normal Light Sensor.

I don't know what the Item Switch Probe/Programmable Switch Probes are supposed to do, but I tried using one on a camo'd block and it crashed my game client. 

Similarly, I've no clue what the Iron/Diamond Exposing Helmets are supposed to do.

Hope this helps. :)

**Comment by Wyn-Price** [comment]
Are these issues in 1.11.2 as well ?

**Comment by Ayasu** [comment]
I can't speak for 1.11.2, our server is still 1.10.2

**Comment by Wyn-Price** [comment]
Ok. I've been working on a completely new rendering system for 1.12.2 that allows optifine connected textures to work with the secret rooms mod, and I'm almost finished with it, so after I've done that I'll get straight to fixing up 1.10.2 and adding the recipes for 1.11.2

**Comment by Wyn-Price** [comment]
Could you give me the crash report for the switch probe. Also the helmet is meant to highlight where the secret rooms mod blocks are, but that might not work

**Comment by Ayasu** [comment]
All good. :) Using Minetweaker as a "workaround" to make the recipes(just building them based from old wikipages and stuff) for now. 

As always, I'm patient and look forward to when you're able to get it all working! \o/

Crashlog attached:
[crash-2017-12-14_00.14.42-client.txt](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1558349/crash-2017-12-14_00.14.42-client.txt)

**Comment by Wyn-Price** [comment]
That crash is to do with GUI screens and the switch probe

**Comment by Wyn-Price** [comment]
I couldnt find any issues with the pressure plates
