### ISSUE TITLE
[1.12.2] doubleing doors [Bug]

### ISSUE THREAD

**Issue by JonasCiss** [AbrarSyed/SecretRoomsMod-forge#209]
If you place a door it what be displayed as two blocks. If you break the lower you will get two secret doors instead of one.

**Comment by Wyn-Price** [comment]
What do you mean it will be displayed as two blocks

**Comment by Wyn-Price** [comment]
Is the issue here that theres is 2 drops from the door, or am I missing something

**Comment by JonasCiss** [comment]
You place one door and go two doors back. 

I mean that it has two hitboxes after it had been placed.

**Comment by Wyn-Price** [comment]
I'm still confused about what you mean. You could show some screenshots of what you mean

**Comment by JonasCiss** [comment]
You have to place one secret door.

![2017-12-16_19 14 02](https://user-images.githubusercontent.com/26455012/34073247-a8e7d59c-e295-11e7-84b6-abc7cc39c182.png)

Then break the upper half of it (not the lower, sorry for that).  Two items instead of one will appear.

![2017-12-16_19 14 34](https://user-images.githubusercontent.com/26455012/34073257-d0845706-e295-11e7-8a56-4af11ed6a5fb.png)

**Comment by Wyn-Price** [comment]
Can you pick up both these items or is one item a ghost item

**Comment by JonasCiss** [comment]
You could pick up both. It is no graphical issue.

**Comment by Wyn-Price** [comment]
Ok I know how to fix this I'll be able to do it for tonight/tommorow

**Comment by JonasCiss** [comment]
I will test it when it is finished.

**Comment by Wyn-Price** [comment]
Is [this](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1565093/secretroomsmod-1.12.2-5.1.11.zip) version all good?

**Comment by JonasCiss** [comment]
Everything works now, thanks!
