### ISSUE TITLE
[1.12.2] anamiation of open doors is broken

### ISSUE THREAD

**Issue by JonasCiss** [AbrarSyed/SecretRoomsMod-forge#210]
Maybe I am wrong but I the 1.7.10 version the doors could be opened. In the 1.12.2 version they always show up the same texture.

This door is closed. 
![2017-12-21_17 40 46](https://user-images.githubusercontent.com/26455012/34270911-4150f406-e68a-11e7-98d8-4522c3c6e313.png)

and this door is open
![2017-12-21_17 40 48](https://user-images.githubusercontent.com/26455012/34270920-4dd9d986-e68a-11e7-8efd-35ee4e6441d2.png)

Is that intended or a bug?

**Comment by Wyn-Price** [comment]
That isnt good! Could you place a door on a normal area, without blocks by it, and screenshot it. Also, are you using Optifine.

**Comment by Wyn-Price** [comment]
Also what version of the one probe are you using. There should be support for that.

**Comment by JonasCiss** [comment]
OptiFine 1.12.2 HD U C7

That is not the OneProbe. It is HWLYA. https://minecraft.curseforge.com/projects/hwyla 

What do you mean with normal area? How could I place the door if there is no ground beneath?

**Comment by Wyn-Price** [comment]
Ah yes this is an issue with C7. Currently c7 source code isnt released. So Im not able to make it work fully. C6 works perfectly though. Ill add a check to see if if the version of Optifine is correct

**Comment by Wyn-Price** [comment]
If you look in the logs, it should be spamming you with warnings?

**Comment by JonasCiss** [comment]
[2017-12-21-4.log.gz](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1580397/2017-12-21-4.log.gz) 
You mean something like that?

**Comment by JonasCiss** [comment]
That is the latest one.

**Comment by JonasCiss** [comment]
I took a picture of that without Optifine. It seems that Optifine is not resposible for the behavior.
![2017-12-30_10 29 22](https://user-images.githubusercontent.com/26455012/34453164-d2f6a19e-ed4c-11e7-92c2-1ef1fbe260e0.png)
![2017-12-30_10 29 30](https://user-images.githubusercontent.com/26455012/34453165-d77d533e-ed4c-11e7-9cbd-df3c9b17daa4.png)

**Comment by Wyn-Price** [comment]
Ok that's interesting.ill look more into it

**Comment by Wyn-Price** [comment]
Could you send me the latest.log after playing this world, without optifine

**Comment by JonasCiss** [comment]
[2017-12-30-1.log.gz](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1594379/2017-12-30-1.log.gz)

**Comment by Wyn-Price** [comment]
There should be a file called latest.log, not in a .gz file. Could you play the test world, then send me that file

**Comment by JonasCiss** [comment]
[latest.log](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1594389/latest.log)

**Comment by Wyn-Price** [comment]
Ok I'm free in around an hour so I'll be able to look into it then.

**Comment by JonasCiss** [comment]
You can upload a file if you need it to get tested.

**Comment by Wyn-Price** [comment]
Yeh that would be probably something I need to do

**Comment by Wyn-Price** [comment]
Im unable to replicate this without using Optifine C7. Are you sure youre not using that

**Comment by JonasCiss** [comment]
I am pretty sure I removed it. I will test it again.

**Comment by JonasCiss** [comment]
Seems that I was extremely confused.
However, if Optifine C 6 is installed everything works fine. Only C 7 seems to be bugged.

**Comment by Wyn-Price** [comment]
Ok that makes sense. Im working on a fix for C7 at the moment

**Comment by JonasCiss** [comment]
fixed in 5.1.13

**Comment by Wyn-Price** [comment]
Glad it finally was fixed. Sorry I took so long, it was hard to find a way to manipulate Optifine in a way so this would work
