### ISSUE TITLE
Exception loading model for variant

### ISSUE THREAD

**Issue by CcytherR** [AbrarSyed/SecretRoomsMod-forge#211]
Hey, just a heads up, seems theres some models missing https://pastebin.com/PJeuFcVg just search for Exception loading model for variant then your mod name through that log to see the relevant error or whatever.

Thanks.

**Comment by Wyn-Price** [comment]
I couldn't find any relating to secretroomsmod. It might be because I'm on mobile and it's harder to search. Could you find the line and comment what it says
