### ISSUE TITLE
Rendering performance issue with doors in 1.12

### ISSUE THREAD

**Issue by Anesos** [AbrarSyed/SecretRoomsMod-forge#212]
Made some neat hidden doors and was really stoked about the mod, but found it was causing massive frame rate issues. I was going from over 80 fps most of the time down to 15 fps if I stood in the right spot. We only had 4 secret doors and haven't done any tech yet, so not much to redraw.

Using Sampler, I found that the doors are causing redraws and that the issue persists even after the door is broken. The attached picture shows white crosshairs on blocks causing re-rendering. You can see both the door that was on the glass (botania) room in the back and 2 blocks on the grass where I put a door down and then broke it are causing issues. 

After removing all 4 doors and some time (unloaded chunks? server restart?), I found the frame rate issue was resolved. 

Pack: FTB Revelations 1.0

![image](https://user-images.githubusercontent.com/17343257/34508365-3c54d2fc-eff3-11e7-9fce-c53a62804052.png)

**Comment by Wyn-Price** [comment]
This was an issue I left in from debugging. Thank you so much for this, I was struggling to find out what was causing these performance issues. As for when I can release a new version, probably tommorow, possibly a few days after. I'm leaving to see family tommorow and I don't know if I'll be finished with it by then.

**Comment by Wyn-Price** [comment]
Could you just try [this](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1600834/secretroomsmod-1.12.2-5.1.12.zip) version. Should be better.

**Comment by Anesos** [comment]
Oh good, glad this was helpful and thanks for the quick response! 

I'm playing on a server, so will have to wait for the pack and the server to update before I can test it again.
