### ISSUE TITLE
net.minecraft.block.state.BlockStateContainer$StateImplementation cannot be cast to net.minecraftforge.common.property.IExtendedBlockState

### ISSUE THREAD

**Issue by sandalle** [AbrarSyed/SecretRoomsMod-forge#213]
I get a client crash with `java.lang.ClassCastException: pl.asie.foamfix.common.FoamyBlockState cannot be cast to net.minecraftforge.common.property.IExtendedBlockState` now which mentions Secret Rooms Mods. While it mentions FoamFix, per https://github.com/asiekierka/FoamFix/issues/101 I still get the same crash without FoamFix installed, just now referencing the non-overloaded function `java.lang.ClassCastException: net.minecraft.block.state.BlockStateContainer$StateImplementation cannot be cast to net.minecraftforge.common.property.IExtendedBlockState`. Open Modular Libs has https://github.com/OpenModularTurretsTeam/OMLib/issues/10 tracking this as OMLib is mentioned in the crash, too.

Crash report: [crash-2018-01-06_14.51.25-client.txt](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1609306/crash-2018-01-06_14.51.25-client.txt)

Minecraft: 1.12.2
Forge Mod Loader: 14.23.1.2582
Foam Fix: 0.8.3-1.12.2-anarchy
Open Modular Lib: 1.12.2-3.0.0-133
Open Modular Turrets: 1.12.2-3.0.0-230
Secret Rooms Mod: 1.12.2-5.1.12

**Comment by Wyn-Price** [comment]
Ok i just looked into this, nothing to do with my mod, even though it was mentioned. Its caused by OpenModularTurretsTeam. Just a quick heads up, Optifine C7 will cause some weird stuff to happen as its not currently supported. Im working on making it work though
