### ISSUE TITLE
1.11.2 dors and trapdors glitched

### ISSUE THREAD

**Issue by rycoshe** [AbrarSyed/SecretRoomsMod-forge#214]
in the 1.11.2 the doors and trapdors are glitched and don't take the blok aspect

**Comment by Wyn-Price** [comment]
are you using Optifine C7? There is an issue causing that to happen. Currently working on a fix

**Comment by rycoshe** [comment]
ok thank you, i love your mod, is my favorite one but is a lot limiting e unable to use block like dors or trapdors, anywai i notice even dat the block with the sildur's vibrant shaders have different color by the original one.

**Comment by Wyn-Price** [comment]
Try using Optifine C6. It should work

**Comment by Wyn-Price** [comment]
If that doesn't work, there's not much I can do. I'm not really supporting the 1.10.2/1.11.2 as the 1.12.2 version takes full priority.

**Comment by Wyn-Price** [comment]
Are you still there? Is the issue fixed?
