### ISSUE TITLE
Placing a door causes Huge FPS drops in that area

### ISSUE THREAD

**Issue by Agatonsaxx** [AbrarSyed/SecretRoomsMod-forge#215]
Just noticed that, when placing a secret door with the mod Secret rooms causes huge FPS drops in the specific area, and its not just me, it happens for all the client who comes to the specific area.

Anything / Anyone who got some tips or something ?

**Comment by Wyn-Price** [comment]
I'm working on solving this issue, and I'm improving it, but still working on making it better. In the meantime, try using Optifine C6 (still working on C7 support)

**Comment by Agatonsaxx** [comment]
Works like a charm ! got any clue about whats causing this issue?

**Comment by Wyn-Price** [comment]
It's something to do with the inner workings of Minecraft, whixh Optifine fixes. I'm looking for into why it's all happening, so I can possibly fix it for people not using Optifine

**Comment by Wyn-Price** [comment]
BTW, In 5.1.13 i added support for Optifine C7 and C8, in case you were still on C6

**Comment by Agatonsaxx** [comment]
Alright ! Yeah was still on C6, will check it out later this evening (Y) Thanks for the heads up!

**Comment by MrNinja93** [comment]
Not just doors are affected seems most of the mods blocks are, once placed they just keep firing render updates.

**Comment by Wyn-Price** [comment]
Are they Still doing that. I'll look into it more, they shouldn't be doing that. That would explain the lag

**Comment by MrNinja93** [comment]
Just double checked on the latest version and you seem to have fixed the render update spam with the changes you made :D

**Comment by Wyn-Price** [comment]
OK good. If you coming from the feed the beast pack, then try updating the mod, as the version they have is the version that causes fps drop
