### ISSUE TITLE
Ticking Entity Crash with 5.2.2

### ISSUE THREAD

**Issue by BrisingrAerowing** [AbrarSyed/SecretRoomsMod-forge#218]
**Optifine?**: No
**If so what version**: N/A
**Does adding/removing Optifine affect the issue?**: Not testable (Incompatible with other mods)

[Crash Log](https://gist.github.com/BrisingrAerowing/7bf9ef9b69ad3a3edb4ed46d46fde836)

Got this when entering a SP world.

**Comment by Wyn-Price** [comment]
Ah ok I see what's happening here. If you create the world on 5.2.1 then load it up in 5.2.2, it'll work fine
