### ISSUE TITLE
[1.12] "Crash" without Crash

### ISSUE THREAD

**Issue by MasterEnderman** [AbrarSyed/SecretRoomsMod-forge#219]
I'm not using Optifine.

If you play with the mod it randomly prints a crashreport in the console but the game doesn't crash.
Forge: 14.23.1.2602
Secret Rooms: 5.2.2
Crash-Report: https://pastebin.com/5pQ8SgVQ

**Comment by Wyn-Price** [comment]
Yeh this is a bug that passed through my testing. I've fixed it for the next version, just curseforge is going through maintenance so I can't update it

**Comment by Wyn-Price** [comment]
Also just note, that this bug will cause the game to crash when creating a new world in single player. If you create a world in the 5.2.1, then it'll work
