### ISSUE TITLE
[1.12.2] Removing Energized Paste from a block drops in Creative mode

### ISSUE THREAD

**Issue by Lordmau5** [AbrarSyed/SecretRoomsMod-forge#221]
### Which version of Secret Rooms Mod is installed?
1.12.2-5.2.3

### Is Optifine installed? If so, which version,
- [x] Yes
- [ ] No

**Version:** 1.12.2 HD U C8

### If Optifine is installed, does removing it affect the issue?
- [ ] Yes
- [x] No

### Detailed explanation of the issue
When a camouflaged block is shift-rightclicked, the Energized Paste is being dropped.

In Survival, that seems okay - though I'd prefer if it **first attempts to put the item into your inventory** before dropping it in-world, if possible.

In Creative, however, it drops the Energized Paste ("formatted").
I am not sure if this is intended, though when you're in creative you aren't using up the item anyway, so I feel it's a bit... useless to drop it there.

**Comment by Wyn-Price** [comment]
It was intended to drop "formatted", but I can remove the creative mode thing. Also thats a good idea, trying to add it to your inventory
