### ISSUE TITLE
May I upload this mod on curse (compiled)

### ISSUE THREAD

**Issue by MrDiamond123** [AbrarSyed/SecretRoomsMod-forge#223]
I wish for your permission to upload this mod onto CurseForge

I know it is/was under LGPL 3.0 but I do still wish for permission (some people are salty about if its for real and I heard I need permission on curse to upload other people's mod) 
I will even put you as Author on the mod page so they know YOU are making the mod

**Comment by MrDiamond123** [comment]
NVM JUST SAW THE PAGE 

DERPPPP!!!

**Comment by Wyn-Price** [comment]
[Isnt this on curseforge already](https://minecraft.curseforge.com/projects/secretroomsmod/)

**Comment by MrDiamond123** [comment]
The forum page needs to be updated :P

**Comment by Wyn-Price** [comment]
Coudl you link it to me? Ill update it now

**Comment by MrDiamond123** [comment]
http://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1276042-v4-7-1-beta-secretroomsmod-malsis-doors-compat

**Comment by Wyn-Price** [comment]
Ah, I cant edit the page. Ill contact AbrarSyed and see if he can update it

**Comment by MrDiamond123** [comment]
Okay

**Comment by MrDiamond123** [comment]
And this is why you update your forum page :P

**Comment by Wyn-Price** [comment]
Yeh thers nothing I can really do. Youll just have to wait
