### ISSUE TITLE
java.lang.ClassCastException: com.wynprice.secretroomsmod.render.FakeRenderChunkListed cannot be cast to net.minecraft.client.renderer.chunk.ListedRenderChunk

### ISSUE THREAD

**Issue by xAlicatt** [AbrarSyed/SecretRoomsMod-forge#225]
**Optifine?**: No
**If so what version**: N/A
**Does adding/removing Optifine affect the issue?**: N/A

This is for the 1.12.2-5.2.5 version of the mod. I'd have to go back and look, but I think I started getting this error a few versions ago and it's still not fixed.

I'm able to start the game fine, but as soon as I load into a world (only tested on singleplayer) my game shuts down and crashes.

Crash log: https://gist.github.com/xAlicatt/8bbd00f4eab57f433afe042c669e70ab

**Comment by Wyn-Price** [comment]
Toggling vbos will fix this for now. I know why this is happening

**Comment by xAlicatt** [comment]
Afaik, I don't have VBOs on anyway...but I'll check and report back.

**Comment by Wyn-Price** [comment]
Turning them on will solve it for now
