### ISSUE TITLE
WALIA/HWYLA Intergration for packs/players who don't use The One Probe.

### ISSUE THREAD

**Issue by ProxyNeko** [AbrarSyed/SecretRoomsMod-forge#226]
**Optifine?**: No.
**If so what version**: N/A.
**Does adding/removing Optifine affect the issue?**: N/A.

This is a request for HWYLA integration for the mod as more packs use this mod and without it, the blocks show what they are in HWYLA.

[HWYLA A fork of WAILA maintained by TehNut.](https://minecraft.curseforge.com/projects/hwyla)

**Comment by Wyn-Price** [comment]
Sure! Im currently working on a new MC rendering system for this, and other mods, but after then sure

**Comment by Wyn-Price** [comment]
OK finished up new rendering system. Working on this now

**Comment by ProxyNeko** [comment]
Nice I look forward to it. Currently putting together a pack update for later tonight/tomorrow but might this be done before next weekend? Don't mind the wait for something to be done right 👍

**Comment by Wyn-Price** [comment]
Probally will be done either today or in the next few days. Shouldn't be hard to do

**Comment by ProxyNeko** [comment]
Cool I'll keep an eye out for it. Good luck and thanks in advance!

**Comment by Wyn-Price** [comment]
Are you able to test [this](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1735163/secretroomsmod-1.12.2-5.3.1.jar.zip)

**Comment by ProxyNeko** [comment]
Testing now

**Comment by Wyn-Price** [comment]
Thanks!

**Comment by ProxyNeko** [comment]
1st issue: when a lever is placed on a log (Oak Wood in this case) it shows up as "Wood" rather than Oak Wood

**Comment by ProxyNeko** [comment]
Torch Lever has no image next to the info from HWYLA but does show it's name as Torch Lever I guess as intended?

**Comment by Wyn-Price** [comment]
Ok [this](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1735206/secretroomsmod-1.12.2-5.3.1.jar.zip) should fix the wood issue

**Comment by Wyn-Price** [comment]
Ill look into the Torch Lever thing now

**Comment by Wyn-Price** [comment]
Ah thats an issue with HWYLA. It happens with alot of blocks.

![image](https://user-images.githubusercontent.com/15876682/36357920-2c837e30-14fd-11e8-912b-d253616f389f.png)

![image](https://user-images.githubusercontent.com/15876682/36357923-341055a6-14fd-11e8-8767-a1d75f996fc8.png)

**Comment by Wyn-Price** [comment]
I can actually fix this I think

**Comment by ProxyNeko** [comment]
I did just ask @TehNut but he thinks it's an issue with another mod I have installed (WAILA an addon mod)

**Comment by Wyn-Price** [comment]
I have a clean version of HWYLA/WAILA, with the only addon being mine

**Comment by ProxyNeko** [comment]
Same thing on my end

**Comment by Wyn-Price** [comment]
It occured in the original 1.7.10 versions i do belive, its todo with the face that the block dosnt have an item attached to it.

**Comment by Wyn-Price** [comment]
one thing i have noticed:
![image](https://user-images.githubusercontent.com/15876682/36357956-e5ae7bf8-14fd-11e8-8c24-63f72dc8c996.png)
![image](https://user-images.githubusercontent.com/15876682/36357958-ebaa2ae8-14fd-11e8-9e9a-f5fcabc3bf1b.png)

**Comment by TehNut** [comment]
This was solved in one of my many bugfixes. May I see your plugin?

**Comment by ProxyNeko** [comment]
I shall ask Darkhax now should have a reply in a few min

**Comment by Wyn-Price** [comment]
@TehNut problem solved. Was an issue on my side
![image](https://user-images.githubusercontent.com/15876682/36357974-41fc57c2-14fe-11e8-9416-274dde53cdfe.png)
![image](https://user-images.githubusercontent.com/15876682/36357976-45b987fe-14fe-11e8-9a27-549b48540e68.png)
![image](https://user-images.githubusercontent.com/15876682/36357978-50760c08-14fe-11e8-907b-f10c48cdd22c.png)

**Comment by ProxyNeko** [comment]
Herp Derp lol

**Comment by ProxyNeko** [comment]
![2018-02-18_22 57 18](https://user-images.githubusercontent.com/19393068/36358027-1cf6664c-14ff-11e8-88f4-653ef381d654.png)
![2018-02-18_22 57 23](https://user-images.githubusercontent.com/19393068/36358028-1d0d0aa0-14ff-11e8-8922-98dc84d9c08e.png)


Might have noticed another issue not relating to any of this with grass textures being identical rather than the random look of vanilla grass but so far everything else works fine (Bar the texture bug in hwyla's box you just found on your end)

**Comment by Wyn-Price** [comment]
Yeah the grass is currenly acting strange with AO. I think i figured out why, just gotta work on a fix

**Comment by Wyn-Price** [comment]
[heres](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1735218/secretroomsmod-1.12.2-5.3.1.jar.zip) latest version. Should be HWYLA/WAILA bug free

**Comment by ProxyNeko** [comment]
Will give it a final test through now

**Comment by ProxyNeko** [comment]
All works great now Thanks!

**Comment by Wyn-Price** [comment]
Alright. Ill work on some bugs and that AO issue, and ill release a new version either later today or tommorow. Thanks for the help!
