### ISSUE TITLE
Crash involving Secret Redstone and Thut Tech Elevators

### ISSUE THREAD

**Issue by DarkMatterXCIX** [AbrarSyed/SecretRoomsMod-forge#230]
**Optifine?**:Yes
**If so what version**:1.12.2-HD_U_C8
**Does adding/removing Optifine affect the issue?**:No
Version of Secret Rooms - I believe it to be the absolute most recent. 

Here is my Crash Log: https://pastebin.com/xWSks4w0

Just crashed whilst rending a entity from a mod called Thut Tech Elevators, I accidently clicked on the elevator block thingy with redstone camo block, crashed my client side, but not server, and kinda corrupted my world unless I remove the mod but I have so much stuff with this mod lol. If you have any questions let me know!

**Comment by Wyn-Price** [comment]
Ok I know why this is happening. I'm currently rewriting the rendering system so hopefully this should be solved

**Comment by Wyn-Price** [comment]
Is this fixed in latest version (5.3.1)

**Comment by DarkMatterXCIX** [comment]
I havnt tested it as of yet, but I have downloaded, I will see

**Comment by DarkMatterXCIX** [comment]
https://pastebin.com/E1nFySH7

It worked, and then i broke the block, and this happened

**Comment by DarkMatterXCIX** [comment]
not to sure if its your mod honestly, might be thuts elevators not liking the fact its placing 2 of itself camouflaged

**Comment by DarkMatterXCIX** [comment]
i am able to join back in my server though, so it isnt corrupting the world, and honestly i wont even use the camo on that kind of block, it was an accidental bug find at first, so its fine honestly

**Comment by Wyn-Price** [comment]
It's a mixture of both mods. I know how to fix it and I'll get that done for tomorrows update. For now, turning off particle effects *may* fix it

**Comment by DarkMatterXCIX** [comment]
okay, ill be good for now! thanks for the such quick work btw, impressive!!

**Comment by Wyn-Price** [comment]
It's happening when you break the blocks, and SRM tries to get the particles to render. The other mod is assuming that when it's asked for the state to render with, that the position of that state is also the position of the actual block, however with SRM, that's not the case. I'm getting the block state from the tile entities data, it doesn't actually exist in the world. 

If that makes sense

**Comment by DarkMatterXCIX** [comment]
yes, it makes sense, im in no way a coder, but ive been playing mc since 2011 so i understand this kind of stuff lol

**Comment by Wyn-Price** [comment]
2010-2011 minecraft where the days

**Comment by DarkMatterXCIX** [comment]
Agreed.. for sure agreed, wish the modding community was still super big as it used to be. but there are still amazing mods for sure, like this one

**Comment by Wyn-Price** [comment]
Yeah the update from 1.7.10 to 1.8 was a practical rewrite of the whole game. Modding in it was a complete change, and you couldn't just update a mod, you had to rewrite it for later versions. That's what killed off the modding community, the fact that most of the popular mods had to be rewritten in a new program, which for some modders was impossible

**Comment by DarkMatterXCIX** [comment]
exactly!!! 1.7.10 has so so so many good mods!!! its absolutely insane!! I was literally about to say 1.7.10 was the prime time for modding and playing

**Comment by Wyn-Price** [comment]
Modding in 1.7.10 was also (arguably) easier, although there are some 1.8+ features that I'm very glad now exist. Anyway, there's people who've learnt 1.8+ modding and are updating all the mods. When I rewrote Secretroomsmod, I did it all from memory, as looking over the code, mine and Abrars (original creator) coding style are very different, and the code he's using dosent when make sense to me, as the programs are littally completly different

**Comment by DarkMatterXCIX** [comment]
damn... i just wish there was one program everyone used that was super good, and mc was still as popular for modding as 1.7.10 was, i loved playing 1.7.10 cause litterally EVERY mod was out for 1.7.10, and it was so so good

**Comment by Wyn-Price** [comment]
If minecraft released their official modding API this wouldnt have been an issue. With the minecraft official modding API, backwards compatibility would be a thing, meaning you could use mods from 1.7.10, with mods that didn't even exist in 1.7.10. 

To the extent they would work though could be an issue

**Comment by DarkMatterXCIX** [comment]
yeah, that would be insane, why didn't they do it? like what's holding the team back behind that kind of stuff?

**Comment by Wyn-Price** [comment]
Although it would be insane, I don't think Mojang should do it. In an interview, they talked about how they wouldnt be able to do anything the minecraft forge api would be able to do, and that everyone uses the forge API, noone wants to learn a new program. It would be alot of work with very little pay off. If they just work on new content, the many people at the minecraft forge team will get stuff sorted out. 

Besides I like the community aspect of forge, if the official API came out it would be cool and all, but it would create a divide between forge and minecraft, meaning less mods for forge, and less mods for the official API. 

It's better how it is at the moment, with forge being on top, as you don't have to worry about what API a mod would be in, you know it's going to be forge. Also as a mod developer, the thought of 2 APIs isn't nice. Undoubtedly, people would ask a mod developer to convert their mod from one API to the other, and from doing that in the past (1.7.10-1.8), it can be very painful, especially when your still working on the mod, or when you find bugs, as you have to update the other version, and if you've changed alot it can become a real pain.

Anyway that's enough rambling

**Comment by Wyn-Price** [comment]
Yeah introducing a new API will probably do worse than it'll do better.

And with forges asm system (where you can change vanilla code), there's actually nothing you can't do. If you wanted to, someone could rewrite the entire game, within a mod

**Comment by DarkMatterXCIX** [comment]
thats insane, but hopefully the modding community grows as im still seeing new mods pop up everyday, i just hope the old mods catch up like Flans, though im in touch with minecraft transport simulator and they are doing apart of the same idea, adding content packs and so forth, its pretty damn neat

**Comment by Wyn-Price** [comment]
The modding community definitely isn't dead, just used to be much more prominent

**Comment by DarkMatterXCIX** [comment]
good, I aint into the modding community as much as I used to be so I havn't had a great insite as much as actual modders do, but I sure do it keeps growing cause it sure ain't dying

**Comment by Wyn-Price** [comment]
Recently, like 1.10-1.12, it seems to be growing back, as more old mods are redeveloped.

Still nothing like the 1.7.10 Golden days

**Comment by DarkMatterXCIX** [comment]
for sure, hopefully it can get another golden age, history does repeat itself, like maybe MC 1.13 may come back with some amazing stuff. I guess time will tell

**Comment by Wyn-Price** [comment]
I looked into some of the code for 1.13 and it looks like another rewrite, however nowhere near as bad as 1.7.0-1.8. hopefully it doesn't drive away people though

**Comment by DarkMatterXCIX** [comment]
so will mod porting be tedious or easy?

**Comment by Wyn-Price** [comment]
Should be easy. I didn't look much but it looks like porting SRM would take like a week to 2 weeks. For larger mods it could take a month or so. Hard to tell at this stage

**Comment by DarkMatterXCIX** [comment]
damn, well hopefully its butter and not pudding

**Comment by Wyn-Price** [comment]
Yeah hopefully it doesn't bring up too many issues. I'll be updating SRM no matter how long it takes, can't say the same for other developers

**Comment by DarkMatterXCIX** [comment]
thats always super nice to hear, hopefully they all have that same mind set

**Comment by Wyn-Price** [comment]
Speaking to most of them on discord, it seems like they do have the same mindset, and hopefully will follow through

**Comment by DarkMatterXCIX** [comment]
thats good, on discord im only in touch with 8 different mod discord channels but a lot of other modders talk in them aswell so im not sure how many i talk to exactly but a lot of em are excited for the next update and to get to work

**Comment by Wyn-Price** [comment]
The /r/feedthebeast discord is the only minecraft related one I'm really in, apart form a few YouTuber discords.

**Comment by DarkMatterXCIX** [comment]
lol, yeah im in like buildcraft, Built Broken Modding which has like ICBM and 8 other mod developers in it, and Minecraft transport simulator, Mo Creatures which is toxic AF, and MjrLegends which is Galacticraft

**Comment by DarkMatterXCIX** [comment]
Mo creatures mod developer is a straight up asshole, he kicked me for sending in a crash report and told me to f off, like yeah okay

**Comment by Wyn-Price** [comment]
Some devs, especially the OG's can be over themselves. Noone in the feedthebeast one has been like that though, it's got much more of a sense of community than those private discords where the owners think they're God's

**Comment by DarkMatterXCIX** [comment]
That's exactly the issue, some are just crazy, and the some are so open to anything like they are so chillaxed.

**Comment by Wyn-Price** [comment]
The chill developers are so much better than the other type. I've worked with both types before, and the ones who think theyre gods gift often can code better than the ones that don't, but it's way harder to work with them. You'll often see mod developers like that working alone, and although I prefer working alone, I am able to work with other people, and have done so in the past

**Comment by DarkMatterXCIX** [comment]
Ya, well let's just hope everything works out pretty damn smooth. And I have an idea for ur mod, i know this sounds crazy, have a way to make a big hatch that opens that's camouflage like a giant rocket hatch that opens up in the ground, which then in turn after opening can launch like a 10x10 rocket from galacticraft or something, that could be epic, I know it's big, but if u made one with configurable size it would be neat2

**Comment by DarkMatterXCIX** [comment]
Like an oversized trapdoor

**Comment by Wyn-Price** [comment]
Couldn't you already do this with camoflage gates?

**Comment by Wyn-Price** [comment]
Camo Gates arnt like normal gates. They extend I think 10 blocks in the direction they're facing when power ed

**Comment by DarkMatterXCIX** [comment]
Soooooo.. r u telling me I can already do that with ur Gates? And they all open into one giant hole?

**Comment by DarkMatterXCIX** [comment]
So like a giant rocket from galacticraft can launch out of the ground through a opened up camo trapdoor?

**Comment by DarkMatterXCIX** [comment]
That's like 10x10?

**Comment by Wyn-Price** [comment]
You could make a 20x20 hole, and line 2 opposite edges with camo Gates and hook up redstone to power those dates whenbyoy want it to be closed

**Comment by Wyn-Price** [comment]
Gates have to be facing inwards

**Comment by DarkMatterXCIX** [comment]
And it'll cover the entire hole up? So it's invisible?

**Comment by DarkMatterXCIX** [comment]
*camoed

**Comment by Wyn-Price** [comment]
The blocks made by the gate will be camoed the same as the gate block. Currently there's no animation, they just appear and disappear, but I plan to change this

**Comment by DarkMatterXCIX** [comment]
Okay cool! I'll test it out and see how it goes later lol, otherwise check this picture out so u might get a better idea https://i.pinimg.com/originals/e1/f2/cd/e1f2cd0065cce3dd7ee350dc1758c5b5.jpg

If something like this was made that was bigger and did the same thing but camouflaged, it was be cool, but if this already works then hell ya

**Comment by Wyn-Price** [comment]
It wouldn't be exactly like that, just the floor would disappear and reappear, however I'm working on making it animated, so the floor extends inwards and ourwards, slower than instantly

**Comment by DarkMatterXCIX** [comment]
And you sir! are a LEGEND! Thank YOU!

**Comment by Wyn-Price** [comment]
Is issue fixed? Im going through and cleaning out all the issues and was wondering if I could close this

**Comment by DarkMatterXCIX** [comment]
Yeah I can close it.
