### ISSUE TITLE
[1.12.2] Client Crash Tesselating block model .. java.lang.ArrayIndexOutOfBoundsException: 28

### ISSUE THREAD

**Issue by Morpheus1101** [AbrarSyed/SecretRoomsMod-forge#232]
Don't use Optifine.
Forge v*.2.2615
SRM v5.3.2

Crash log @ https://gist.github.com/Morpheus1101/47f665da2f5cac33a69cc6bbe19ee8f6

On a side note, you have to remove the offending block from world otherwise you will continue to crash once you enter the game or load in that chunk

**Comment by Wyn-Price** [comment]
Does this happen with every SRM block or is it just the door. Also, is it every door, or just that one instance

**Comment by Morpheus1101** [comment]
This occurs with the Iron Door as well, but all other blocks worked fine from testing

**Comment by Wyn-Price** [comment]
Does this still happen in the latest version ?

**Comment by Wyn-Price** [comment]
Also, try loading up a new world, then placing a new door and see if that works

**Comment by Morpheus1101** [comment]
I always test using a brand new world each time & this issue is fixed in current version thankyou :)
