### ISSUE TITLE
Gate block crashes on server startup

### ISSUE THREAD

**Issue by evan1026** [AbrarSyed/SecretRoomsMod-forge#233]
I was able to place some gates and have them working in my world, but after a server reboot it is consistently crashing with this error log:

[https://pastebin.com/h9MUcsFt](https://pastebin.com/h9MUcsFt)

I also see that immersiveengineering is in the stacktrace, but since your function is at the top I'm reporting it here first. If after investigation you believe this is their issue and not yours just let me know and I'll report it to them.

**Optifine?**: No
**If so what version**: N/A
**Does adding/removing Optifine affect the issue?**: N/A

**Comment by Wyn-Price** [comment]
Dont bother with ImersiveEngerneering, it seems to be all to do with me. Ill look into it tommorow

**Comment by Wyn-Price** [comment]
OK i think ive fixed it. Could you try [this ](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1799407/secretroomsmod-1.12.2-5.4.1.jar.zip) build? Im busy for the next couple of hours so i wont be able to do anything, but will be able to reply and stuff

**Comment by evan1026** [comment]
No, looks like the same crash https://pastebin.com/TaX0JhHq

Would it help if I sent you the world file? I tried to reproduce the bug in another world with the same setup but it worked fine there. Maybe the save got corrupted?

**Comment by Wyn-Price** [comment]
It looks like a corruption. If you could send over the world file that would be useful

**Comment by evan1026** [comment]
https://www.dropbox.com/s/gtvhri9430kuk6d/Realistic.bak.zip?dl=0

This is for the FTB Revelation modpack (I also added Dynmap and DynmapBlockScan but those shouldn't affect the world)

**Comment by Wyn-Price** [comment]
Ok thanks! I should have a new build with the fix (and some new features) out by tommorow, however because its a modpack youll have to manually replace the file

**Comment by Wyn-Price** [comment]
Woudl you be able to just test this build out. (Make sure to back up your world first, as ive made a change that might mess some stuff up). Could you also send the log from loading up the world if you can do it

**Comment by Wyn-Price** [comment]
Forgot to link .zip sorry! [secretroomsmod-1.12.2-5.4.1.jar.zip](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1799695/secretroomsmod-1.12.2-5.4.1.jar.zip)

**Comment by evan1026** [comment]
Alright, I'll try it out as soon as I get time

**Comment by Wyn-Price** [comment]
@evan1026 where you able to test anything?

**Comment by evan1026** [comment]
Not yet, sorry. I work full time so I haven't had the free time yet. I'm planning to try it out either tomorrow or over the weekend

**Comment by Wyn-Price** [comment]
thats fine, im busy as well

**Comment by evan1026** [comment]
Still crashed, new error though
https://pastebin.com/FcDMjNmu

**Comment by Wyn-Price** [comment]
Can you try [this](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1822824/secretroomsmod-1.12.2-5.5.3.jar.zip) version?

**Comment by evan1026** [comment]
Yeah that actually worked. The gates aren't disguised as the right thing, but I suspect that much was already broken to begin with

**Comment by Wyn-Price** [comment]
Yeah the gates are corrupted for whatever reason. Placing them again should solve it

**Comment by evan1026** [comment]
Just got the issue again (haven't updated to the new version yet). I'm wondering if maybe there's an issue with how the blocks are saved that's causing the corruption. Might be something to look into.

**Comment by Wyn-Price** [comment]
The blocks are saved with NBT tags, I dont exactly know why it wouldnt work. I add a custom log to help debug everything. 

Is the world crashing or are the blocks just replaced with stone

**Comment by evan1026** [comment]
I updated to the new version and loaded in the world. All the blocks were still their appropriate types but half of the gates retracted themselves and half didn't. Also, they lost their disguises and became disguised as dirt

**Comment by Wyn-Price** [comment]
disguised as dirt? Thats intresing. The default for all blocks when they crash is stone. Can you send over the `fml-client-latest.log`

**Comment by evan1026** [comment]
Sorry sorry, I meant stone not dirt. I will send you all of the logs I can find since that may not have been the most recent time the server was started

**Comment by evan1026** [comment]
[logs.zip](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1862209/logs.zip)

**Comment by Wyn-Price** [comment]
Im not sure why the worlds breaking. Ill impliment a custom logging system for next release to help with debugging
