### ISSUE TITLE
[BUG] One Way glass dies

### ISSUE THREAD

**Issue by Akitori** [AbrarSyed/SecretRoomsMod-forge#234]
optifine 1.12.2 HD U8

basically this

https://cdn.discordapp.com/attachments/383141601200832515/422532068334108687/5dbcfe84-ca65-4d51-9223-a0a2dd1ec36d.gif

**Comment by Wyn-Price** [comment]
Does it happen without optifine?

**Comment by Wyn-Price** [comment]
Looking again, it might not be optifine. Does placing the secret glass work on other blocks (not stone). Does it work when it's not connected to other secret glass blocks

**Comment by Akitori** [comment]
it works when not connected as far as i'm aware. when all the glass is connected/any block updates it, it turns to stone.

**Comment by Wyn-Price** [comment]
Does it turn to stone even when you haven't set it as stone? If so that means that somewhere, there's an null blockstate being returned. I might have fixed this in Dev so I'll send you some builds to test out tomorrow

**Comment by Akitori** [comment]
no it turns to the block its disguised as fully

**Comment by Wyn-Price** [comment]
Ok I'll look into it

**Comment by Wyn-Price** [comment]
OK ive rewritten a huge amount of the rendering system. Im going to release a new version on curseforge later today. At the current point in time, theres no support for Optifine Connected Textures, but there will be in time

**Comment by Wyn-Price** [comment]
@Akitori have you tried the new version on curseforge? It should work

**Comment by Wyn-Price** [comment]
@Akitori ?
