### ISSUE TITLE
Crash / Hang on world load

### ISSUE THREAD

**Issue by BrisingrAerowing** [AbrarSyed/SecretRoomsMod-forge#235]
**Optifine?**: No
**If so what version**: N/A
**Does adding/removing Optifine affect the issue?**: N/A

I was getting a crash when trying to load my game, and it turns out the update checker is broken when the player is not loaded when it runs.
[Crash Stacktrace](https://gist.github.com/BrisingrAerowing/d2b404e62988b2dec64b82a258014c1a)
(The crash is actually a hang on world load, so no actual crash log)

**Comment by Wyn-Price** [comment]
@BrisingrAerowing is this fixed in the new version?

**Comment by BrisingrAerowing** [comment]
Seems to be.
