### ISSUE TITLE
[1.12.2] SecretRooms Mod loading Client Side Code on Server side in v5.5.0

### ISSUE THREAD

**Issue by Morpheus1101** [AbrarSyed/SecretRoomsMod-forge#236]
**Optifine?**:  Hell No :D

Forge *.2625
SR v5.5.0

Log @ https://gist.github.com/Morpheus1101/6fd203b78911a27592d6a78fe14c58c4

**Comment by Wyn-Price** [comment]
Oops I forget to check this. Fix coming out in less than an hour

**Comment by Morpheus1101** [comment]
v5.5.1 still has this issue

**Comment by Wyn-Price** [comment]
@Morpheus1101 can you send the fml-client-latest.log

**Comment by Morpheus1101** [comment]
[fml-server-latest.log](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1822105/fml-server-latest.log)

Havent attempted to load it on client side yet since the server dosent load

**Comment by Wyn-Price** [comment]
Is that on the server? The coremods being loaded for some reason.

**Comment by Wyn-Price** [comment]
I'll add more checks now

**Comment by Morpheus1101** [comment]
Yes it is on server

**Comment by Wyn-Price** [comment]
Are you able to test [this](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1822209/secretroomsmod-1.12.2-5.5.2.jar.zip)? It should all be working now.

**Comment by felesmortis** [comment]
@Wyn-Price That works for me.

**Comment by Wyn-Price** [comment]
@felesmortis ok, I'll mark this as fixed and release a new version on curseforge

**Comment by Morpheus1101** [comment]
This is occurring again in 5.5.3

**Comment by Wyn-Price** [comment]
Oof sorry about that

**Comment by Wyn-Price** [comment]
@Morpheus1101 Does [this](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1844508/secretroomsmod-1.12.2-5.5.4.jar.zip) fix it?

**Comment by Morpheus1101** [comment]
Yes it does

**Comment by Majora320** [comment]
@Wyn-Price Still happening for me on 5.5.4

**Comment by Wyn-Price** [comment]
@Majora320 Ok thats weird. Working on a fix now

**Comment by Wyn-Price** [comment]
@Majora320 ok does [this](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1844921/secretroomsmod-1.12.2-5.5.5.jar.zip) version work?

**Comment by Majora320** [comment]
@Wyn-Price Yep, that seems to fix it. Thanks!

**Comment by Majora320** [comment]
I'm now getting a new error when trying to join the server (client side): https://ptpb.pw/-jtb

**Comment by Wyn-Price** [comment]
@Majora320 sorry for taking so long, I didnt see this. Does [this](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1844969/secretroomsmod-1.12.2-5.5.5.jar.zip) version sort out the issue?

**Comment by Majora320** [comment]
@Wyn-Price Yep, that seems to work. Thanks!
