### ISSUE TITLE
Cannot open vanilla chests/trapped chests

### ISSUE THREAD

**Issue by darthvader45** [AbrarSyed/SecretRoomsMod-forge#238]
**Optifine?**: No
**If so what version**: N/A
**Does adding/removing Optifine affect the issue?**: No

Cannot open vanilla trapped chests or regular vanilla chests at ALL while this mod is loaded.  Only with this mod removed can I open chests.  Really game-breaking if I have to break chests to access their contents.

**Comment by Wyn-Price** [comment]
Is the world youre playing in singleplayer or server? Would you be able to send over the world? Does this issue happen when secretroomsmod is on its own, with no other mods?

**Comment by darthvader45** [comment]
Doesn't happen without other mods (I of course needed malisisdoors to test compat).  No idea what mod could cause this as I know of no other mods I installed that mess with chests in any way.

**Comment by Wyn-Price** [comment]
Could you zip up the worlds, mods and configs (if youve changed any) for me to test out

**Comment by Wyn-Price** [comment]
Also malisisdoors compat is like half done

**Comment by darthvader45** [comment]
Okay, it seems that updating Optifine fixes the issue, no idea why that would have any effect on opening chests.

**Comment by quat1024** [comment]
*I'm* confused about how you said you didn't have Optifine installed but the solution to your problem was updating Optifine :thinking: :thinking: :thinking:

**Comment by darthvader45** [comment]
I had it installed, removing it fixed it, decided to check to see if updating would also fix it, and it did.
