### ISSUE TITLE
Continued crashing after adding ghost block of nether brick fence

### ISSUE THREAD

**Issue by iahawk15** [AbrarSyed/SecretRoomsMod-forge#240]
**Optifine?**: No
**If so what version**: N/A
**Does adding/removing Optifine affect the issue?**: N/A

My daughter added a ghost block of nether brick fence, now game crashes shortly after loading. I was able to delete the block between crashes, but the crash persists.

Running 1.12.2 with Forge Loader 1.12.2-14.23.2.2611. The original crash happened using Secret Rooms 5.2.7. Updating to 5.5.2 did not resolve issue.

Other mods on during original crash:
Custom NPC's 1.12.2
Pam's Harvest Craft 1.12.2q
Chisels and Bits 14.8

Original Crash report: 
[crash-2018-03-23_08.29.52-client.txt](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1842544/crash-2018-03-23_08.29.52-client.txt)

After removing Custom NPC's and Pam's Harvest Craft:
Crash persists at about 5 seconds after load.

After also removing Chisels and Bits 14.8:
Game freezes (not responding) at about 15 seconds after load.

Final Crash Report:
[crash-2018-03-23_11.19.31-client.txt](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1842527/crash-2018-03-23_11.19.31-client.txt)

Thank you in advance for any help you can provide. Please let me know if any additional information is needed. Thanks again!

**Comment by Wyn-Price** [comment]
Looks like the blocks got corrupted. I seem to be blindly assuming its not. I can fix the crash, but youll need to replace the fence

**Comment by Wyn-Price** [comment]
In fact looking over the tileEntity code, I think Im going to rewrite it. It dosnt seem to be well optimized, at I can see multiple flaws

**Comment by iahawk15** [comment]
OK, I have no worries about the fence. At this point, she just wants to be able to play the world again!

Should I wait for an update and use latest version?

Thanks so much for your help!

**Comment by Wyn-Price** [comment]
Ill send you a modified version to see if it its all fixed. ETA around 15-20 minutes I guess?

**Comment by iahawk15** [comment]
oh yeah, that's great. I'll check back in a bit. thanks!

**Comment by Wyn-Price** [comment]
@iahawk15 Make sure to back up the world before testing [this](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1842797/secretroomsmod-1.12.2-5.5.4.jar.zip). Ive made major modifications to how the data is saved, and although Ive testing it, it may corrupt things.

**Comment by Wyn-Price** [comment]
Also once youve used that, could you send over the `fml-client-latest.log` and the `latest.log`, just so i can see whats going on

**Comment by iahawk15** [comment]
Just to clarify, I should run 5.5.4 alone and not along side 5.5.2 as a patch, correct? If so, here's the results of running 5.5.4 alone...

Crash message:
The game crashed whilst tesselating block model
The game crashed whilst tesselating block model
Error: java.lang.NullPointerException: Tesselating block model

Crash Report:
[crash-2018-03-23_12.50.13-client.txt](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1842854/crash-2018-03-23_12.50.13-client.txt)

fml-client-latest:
[fml-client-latest.log](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1842864/fml-client-latest.log)

latest:
[latest.log](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1842865/latest.log)

**Comment by Wyn-Price** [comment]
Running it alone is correct. However you can run it with other mods. 
Could you try [this](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1842906/secretroomsmod-1.12.2-5.5.4.jar.zip) version, and also send me the two logs.

**Comment by iahawk15** [comment]
OK, the game will run. All secret blocks are functional, but visibility reverted to stone.

[fml-client-latest.log](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1842937/fml-client-latest.log)

[latest.log](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1842939/latest.log)

**Comment by Wyn-Price** [comment]
Ok, it just looks like corrupted blocks. Not sure why they where corrupted but I hope rewriting the saveing of stuff should fix it

**Comment by Wyn-Price** [comment]
@iahawk15 Wait, when you mean all secretrooms blocks, did you mean just the fence that broke everything, or every single srm block?

**Comment by iahawk15** [comment]
every single srm block. Doors, ghost blocks, one-way glass, etc...

**Comment by Wyn-Price** [comment]
right, ok Ive made a mistake with loading tile entities

**Comment by Wyn-Price** [comment]
do you still have a backup of the world?

**Comment by iahawk15** [comment]
yes, I still have backup.

**Comment by Wyn-Price** [comment]
Ok thats good. Ill send a new version over in around 10 minutes that should keep the mirrored states, when the worlds loaded from backup

**Comment by iahawk15** [comment]
ok, great. I'll check back. Thanks a ton!

**Comment by Wyn-Price** [comment]
wait I know why its not working. This will take around 2 minutes hold on

**Comment by Wyn-Price** [comment]
this might take longer than i first thought. Should be done around 15 minutes

**Comment by Wyn-Price** [comment]
Ok try [this](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1843049/secretroomsmod-1.12.2-5.5.4.jar.zip). Theres some minor rendering issues im fixing right now

**Comment by iahawk15** [comment]
...and it's working! I cannot thank you enough for your diligence with this issue. My daughters are squealing with excitement.

Just in case you need them:
[fml-client-latest.log](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1843126/fml-client-latest.log)
[latest.log](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1843127/latest.log)

Thanks again!

**Comment by Wyn-Price** [comment]
You might see some rendering issues with doors and trapdoors, but im fixing all of that stuff for 5.5.4 which ill release later today
