### ISSUE TITLE
SRM 5.6.0 breaks trapdoor rendering

### ISSUE THREAD

**Issue by BrisingrAerowing** [AbrarSyed/SecretRoomsMod-forge#242]
**Optifine?**: No
**If so what version**: N/A
**Does adding/removing Optifine affect the issue?**: Not Tested (Incompatible with other mods)

SRM v5.6.0 causes wooden trapdoors to render invisible. Reverting to 5.5.5 makes them visible again.

**Comment by Wyn-Price** [comment]
What mods are you using? In dev it renders

**Comment by BrisingrAerowing** [comment]
I'll test my mods and see what's going on.

**Comment by BrisingrAerowing** [comment]
It appears to be a bug with the Malisis Doors compat, as an instance with SRM, Malisis Doors, and Malisis Core exhibits the behavior.

**Comment by Wyn-Price** [comment]
Malisisdoors support is the one thing 5.6.0 sorted out. It works on my end. What version of forge are you using, I might need to update

**Comment by BrisingrAerowing** [comment]
I was using 2631, as Dynamic Surroundings would crash with newer versions. An update to DS that fixes that is available, so I'm updating to 2640. I'll see if the newer Forge works or not.

**Comment by Wyn-Price** [comment]
@BrisingrAerowing Ok ill look into versions 2631+. I dont know if ill have time to do it in the next week or so, as i modjam is on tommorow and im participating in it. Ill look into it tonight but if i cant find a fix itll have to wait. I dont want any underlying problems while modjams going on

**Comment by Wyn-Price** [comment]
@BrisingrAerowing is this issue still occuring in 5.6.1?

**Comment by BrisingrAerowing** [comment]
Yes.

**Comment by Wyn-Price** [comment]
Is this fixed in 5.6.2? Version should be on curse in an hour or 2

**Comment by BrisingrAerowing** [comment]
I’ll check when I get back to my computer.

**Comment by BrisingrAerowing** [comment]
Unfortunately not fixed yet.

**Comment by Wyn-Price** [comment]
Are you running srm on its own? or are there other mods apart from malisisdoors

**Comment by BrisingrAerowing** [comment]
Other mods, but a test with just SRM and Malisis Doors showed the issue as well.

**Comment by Wyn-Price** [comment]
Ok. I won't be able to look into it until Friday, as I have exams leading up until then. But after exams, I'll figure out what's going on

**Comment by Wyn-Price** [comment]
Ok, exams ended. I'll either look into it today or tomorrow

**Comment by ate0ate** [comment]
Sorry I didn't respond sooner, but after putting it through its paces everything seems to be working just fine since updating. Thanks a bunch for the fix. I've got almost 300 mods in my pack and optifine so if it works well there it should be good anywhere lol.

**Comment by MastaC729** [comment]
Ugh, I hate to stir this up but I'm having the issue again on version 5.6.4 of SRM. Here are the versions installed:

SRM: 5.6.4
MalisisDoors/Core: 7.3.0
MalisisCore: 6.4.0
Forge: 14.23.5.2796
