### ISSUE TITLE
[Suggestion]Rename "Ghost Blocks"

### ISSUE THREAD

**Issue by Carnaxus** [AbrarSyed/SecretRoomsMod-forge#253]
I saw your description of the "fake floor" trap and realized that these blocks should be called Poltergeist Blocks, since they prank people. 😆

**Comment by Wyn-Price** [comment]
They've been called ghost blocks since 1.5.2. they're the most iconic part of the mod

**Comment by Carnaxus** [comment]
Ah.  Admittedly, this was only a half-serious suggestion, but it would be a fun name.  Maybe add Poltergeist Blocks as a variant of Ghost Blocks that laughs at you as you fall? 🤣
