### ISSUE TITLE
Stone block texture with optifine

### ISSUE THREAD

**Issue by Josh65-2201** [AbrarSyed/SecretRoomsMod-forge#280]
**Optifine?**:Yes
**Version**:U E4 pre 4
**Does adding/removing Optifine affect the issue?**:yes

This also happens with U E3

**Comment by Hojosa** [comment]
The problem is known, wait for the rewrite of the Mod. 
Why is Optifine not supported? Because its not open source, not very up date most of the time with forge releases and a pain to support because its not open source. I think the last working Optifine release was around D2/D3

**Comment by Josh65-2201** [comment]
ok thanks
