### ISSUE TITLE
My secret room mod

### ISSUE THREAD

**Issue by RAPrograms** [AbrarSyed/SecretRoomsMod-forge#283]
My secret room mod is not working with optifine and I was hoping some one could help me fine a way to make both secret rooms mod and optifine work together 

Minecraft 1.14.4
Forge 28.1.20
optifine preview_Optifine_1.14.4_HD_U_F4_pre5 <PS: I am using this optifine because it’s the only one that works>

Secret rooms - 6.0.1

**Comment by Wyn-Price** [comment]
Go to: https://github.com/Wyn-Price/SecretRooms/ and could you provide more information about how it's not working

**Comment by RAPrograms** [comment]
Well when I place a block down it ether dose not appear or looks like this
![image](https://user-images.githubusercontent.com/56273305/66338959-128b3a00-e93a-11e9-8e3d-9134bbd4d3d6.jpg)

**Comment by Wyn-Price** [comment]
I believe this is an error with optifine compatibility with forge, more specifically, `IModelData` not being handled correctly.

**Comment by RAPrograms** [comment]
Do you know how to fix it

**Comment by Wyn-Price** [comment]
I can't fix it, optifine would need to support the forge model data system
